# Tree Species
For life history, mention common canopy positions
  - information from Ramage et al. 2017
    - dominant canopy are *Liriondendron tulipifera* (tulip poplar), *Carya* spp., *Quercus* spp., *Fraxinus americana* (white ash), *Nyssa sylvatica* (black gum)

##Adoxaceae
### *Sambucus canadensis*	(American black elderberry)
```
Life history (information will be added by Michael)
```
```
Leaf traits (written about or scanned and labeled)
```
```
Annual Recruitment and Mortality
# of trees (stems) in 2013 and 2018:
5-year mortality of trees (stems):
new tree recuitment:
max DBH in sample:
mean DBH in sample:
```
```
Graph of recruiment and mortality
{r echo=false}
hist()
```
```
Graph of species range and distribution
```
```
Graph of species range and distribution within the plot (plot location)
```
Picture of tree cores (with a small blurb)

### *Viburnum acerifolium*	(Mapleleaf viburnum)
```
Life history (information will be added by Michael)
```
```
Leaf traits (written about or scanned and labeled)
```
```
Annual Recruitment and Mortality
# of trees (stems) in 2013 and 2018:
5-year mortality of trees (stems):
new tree recuitment:
max DBH in sample:
mean DBH in sample:
```
```
Graph of recruiment and mortality
{r echo=false}
hist()
```
```
Graph of species range and distribution
```
```
Graph of species range and distribution within the plot (plot location)
```
Picture of tree cores (with a small blurb)

###	*Viburnum prunifolium*	(Black haw)
```
Life history (information will be added by Michael)
```
```
Leaf traits (written about or scanned and labeled)
```
```
Annual Recruitment and Mortality
# of trees (stems) in 2013 and 2018:
5-year mortality of trees (stems):
new tree recuitment:
max DBH in sample:
mean DBH in sample:
```
```
Graph of recruiment and mortality
{r echo=false}
hist()
```
```
Graph of species range and distribution
```
```
Graph of species range and distribution within the plot (plot location)
```
Picture of tree cores (with a small blurb)

###	*Viburnum recognitum*	(Southern arrowood)
```
Life history (information will be added by Michael)
```
```
Leaf traits (written about or scanned and labeled)
```
```
Annual Recruitment and Mortality
# of trees (stems) in 2013 and 2018:
5-year mortality of trees (stems):
new tree recuitment:
max DBH in sample:
mean DBH in sample:
```
```
Graph of recruiment and mortality
{r echo=false}
hist()
```
```
Graph of species range and distribution
```
```
Graph of species range and distribution within the plot (plot location)
```
Picture of tree cores (with a small blurb)

## Annonaceae
### *Asimina triloba*	(Pawpaw)
```
Life history (information will be added by Michael)
```
```
Leaf traits (written about or scanned and labeled)
```
```
Annual Recruitment and Mortality
# of trees (stems) in 2013 and 2018:
5-year mortality of trees (stems):
new tree recuitment:
max DBH in sample:
mean DBH in sample:
```
```
Graph of recruiment and mortality
{r echo=false}
hist()
```
```
Graph of species range and distribution
```
```
Graph of species range and distribution within the plot (plot location)
```
Picture of tree cores (with a small blurb)

##Aquifoliaceae
### *Ilex verticillata* (Common winterberry)
```
Life history (information will be added by Michael)
```
```
Leaf traits (written about or scanned and labeled)
```
```
Annual Recruitment and Mortality
# of trees (stems) in 2013 and 2018:
5-year mortality of trees (stems):
new tree recuitment:
max DBH in sample:
mean DBH in sample:
```
```
Graph of recruiment and mortality
{r echo=false}
hist()
```
```
Graph of species range and distribution
```
```
Graph of species range and distribution within the plot (plot location)
```
Picture of tree cores (with a small blurb)

##Berberidaceae
### *Berberis thunbergii* (Japanese barberry)
```
Life history (information will be added by Michael)
```
```
Leaf traits (written about or scanned and labeled)
```
```
Annual Recruitment and Mortality
# of trees (stems) in 2013 and 2018:
5-year mortality of trees (stems):
new tree recuitment:
max DBH in sample:
mean DBH in sample:
```
```
Graph of recruiment and mortality
{r echo=false}
hist()
```
```
Graph of species range and distribution
```
```
Graph of species range and distribution within the plot (plot location)
```
Picture of tree cores (with a small blurb)

## Betulaceae
### *Carpinus caroliniana*	(American hornbeam)
```
Life history (information will be added by Michael)
```
```
Leaf traits (written about or scanned and labeled)
```
```
Annual Recruitment and Mortality
# of trees (stems) in 2013 and 2018:
5-year mortality of trees (stems):
new tree recuitment:
max DBH in sample:
mean DBH in sample:
```
```
Graph of recruiment and mortality
{r echo=false}
hist()
```
```
Graph of species range and distribution
```
```
Graph of species range and distribution within the plot (plot location)
```
Picture of tree cores (with a small blurb)

###	*Corylus americana*	(American hazelnut)
```
Life history (information will be added by Michael)
```
```
Leaf traits (written about or scanned and labeled)
```
```
Annual Recruitment and Mortality
# of trees (stems) in 2013 and 2018:
5-year mortality of trees (stems):
new tree recuitment:
max DBH in sample:
mean DBH in sample:
```
```
Graph of recruiment and mortality
{r echo=false}
hist()
```
```
Graph of species range and distribution
```
```
Graph of species range and distribution within the plot (plot location)
```
Picture of tree cores (with a small blurb)

## Cannabaceae
### *Celtis occidentalis*	(Hackberry)
```
Life history (information will be added by Michael)
```
```
Leaf traits (written about or scanned and labeled)
```
```
Annual Recruitment and Mortality
# of trees (stems) in 2013 and 2018:
5-year mortality of trees (stems):
new tree recuitment:
max DBH in sample:
mean DBH in sample:
```
```
Graph of recruiment and mortality
{r echo=false}
hist()
```
```
Graph of species range and distribution
```
```
Graph of species range and distribution within the plot (plot location)
```
Picture of tree cores (with a small blurb)

## Caprifoliaceae
### *Lonicera maackii* (Bush honeysuckle)
```
Life history (information will be added by Michael)
```
```
Leaf traits (written about or scanned and labeled)
```
```
Annual Recruitment and Mortality
# of trees (stems) in 2013 and 2018:
5-year mortality of trees (stems):
new tree recuitment:
max DBH in sample:
mean DBH in sample:
```
```
Graph of recruiment and mortality
{r echo=false}
hist()
```
```
Graph of species range and distribution
```
```
Graph of species range and distribution within the plot (plot location)
```
Picture of tree cores (with a small blurb)

## Celastraceae
### *Euonymus alatus*	(Burning bush)
```
Life history (information will be added by Michael)
```
```
Leaf traits (written about or scanned and labeled)
```
```
Annual Recruitment and Mortality
# of trees (stems) in 2013 and 2018:
5-year mortality of trees (stems):
new tree recuitment:
max DBH in sample:
mean DBH in sample:
```
```
Graph of recruiment and mortality
{r echo=false}
hist()
```
```
Graph of species range and distribution
```
```
Graph of species range and distribution within the plot (plot location)
```
Picture of tree cores (with a small blurb)

## Cornaceae
### *Cornus alternifolia*	(Alternate leaf dogwood)
```
Life history (information will be added by Michael)
```
```
Leaf traits (written about or scanned and labeled)
```
```
Annual Recruitment and Mortality
# of trees (stems) in 2013 and 2018:
5-year mortality of trees (stems):
new tree recuitment:
max DBH in sample:
mean DBH in sample:
```
```
Graph of recruiment and mortality
{r echo=false}
hist()
```
```
Graph of species range and distribution
```
```
Graph of species range and distribution within the plot (plot location)
```
Picture of tree cores (with a small blurb)

## Cornaceae
### *Cornus florida*	(Flowering dogwood)
```
Life history (information will be added by Michael)
```
```
Leaf traits (written about or scanned and labeled)
```
```
Annual Recruitment and Mortality
# of trees (stems) in 2013 and 2018:
5-year mortality of trees (stems):
new tree recuitment:
max DBH in sample:
mean DBH in sample:
```
```
Graph of recruiment and mortality
{r echo=false}
hist()
```
```
Graph of species range and distribution
```
```
Graph of species range and distribution within the plot (plot location)
```
Picture of tree cores (with a small blurb)

## Ebenaceae
### *Diospyros virginiana* (Persimmon)
```
Life history (information will be added by Michael)
```
```
Leaf traits (written about or scanned and labeled)
```
```
Annual Recruitment and Mortality
# of trees (stems) in 2013 and 2018:
5-year mortality of trees (stems):
new tree recuitment:
max DBH in sample:
mean DBH in sample:
```
```
Graph of recruiment and mortality
{r echo=false}
hist()
```
```
Graph of species range and distribution
```
```
Graph of species range and distribution within the plot (plot location)
```
Picture of tree cores (with a small blurb)

## Elaeagnaceae
### *Elaeagnus umbellata*	(Autumn olive)
```
Life history (information will be added by Michael)
```
```
Leaf traits (written about or scanned and labeled)
```
```
Annual Recruitment and Mortality
# of trees (stems) in 2013 and 2018:
5-year mortality of trees (stems):
new tree recuitment:
max DBH in sample:
mean DBH in sample:
```
```
Graph of recruiment and mortality
{r echo=false}
hist()
```
```
Graph of species range and distribution
```
```
Graph of species range and distribution within the plot (plot location)
```
Picture of tree cores (with a small blurb)

## Fabaceae
### *Cercis canadensis* (Eastern redbud)
```
Life history (information will be added by Michael)
```
```
Leaf traits (written about or scanned and labeled)
```
```
Annual Recruitment and Mortality
# of trees (stems) in 2013 and 2018:
5-year mortality of trees (stems):
new tree recuitment:
max DBH in sample:
mean DBH in sample:
```
```
Graph of recruiment and mortality
{r echo=false}
hist()
```
```
Graph of species range and distribution
```
```
Graph of species range and distribution within the plot (plot location)
```
Picture of tree cores (with a small blurb)

## Fabaceae
### *Robinia pseudoacacia* (Black locust)
```
Life history (information will be added by Michael)
```
```
Leaf traits (written about or scanned and labeled)
```
```
Annual Recruitment and Mortality
# of trees (stems) in 2013 and 2018:
5-year mortality of trees (stems):
new tree recuitment:
max DBH in sample:
mean DBH in sample:
```
```
Graph of recruiment and mortality
{r echo=false}
hist()
```
```
Graph of species range and distribution
```
```
Graph of species range and distribution within the plot (plot location)
```
Picture of tree cores (with a small blurb)

## Fagaceae
### *Castanea dentata* (American chestnut)
```
Life history (information will be added by Michael)
```
```
Leaf traits (written about or scanned and labeled)
```
```
Annual Recruitment and Mortality
# of trees (stems) in 2013 and 2018:
5-year mortality of trees (stems):
new tree recuitment:
max DBH in sample:
mean DBH in sample:
```
```
Graph of recruiment and mortality
{r echo=false}
hist()
```
```
Graph of species range and distribution
```
```
Graph of species range and distribution within the plot (plot location)
```
Picture of tree cores (with a small blurb)

### *Fagus grandifolia*	(American beech)
```
Life history (information will be added by Michael)
```
```
Leaf traits (written about or scanned and labeled)
```
```
Annual Recruitment and Mortality
# of trees (stems) in 2013 and 2018:
5-year mortality of trees (stems):
new tree recuitment:
max DBH in sample:
mean DBH in sample:
```
```
Graph of recruiment and mortality
{r echo=false}
hist()
```
```
Graph of species range and distribution
```
```
Graph of species range and distribution within the plot (plot location)
```
Picture of tree cores (with a small blurb)

### *Quercus alba*	(White oak)
```
Life history (information will be added by Michael)
```
```
Leaf traits (written about or scanned and labeled)
```
```
Annual Recruitment and Mortality
# of trees (stems) in 2013 and 2018:
5-year mortality of trees (stems):
new tree recuitment:
max DBH in sample:
mean DBH in sample:
```
```
Graph of recruiment and mortality
{r echo=false}
hist()
```
```
Graph of species range and distribution
```
```
Graph of species range and distribution within the plot (plot location)
```
Picture of tree cores (with a small blurb)

### *Quercus coccinea*	(Scarlet oak)
```
Life history (information will be added by Michael)
```
```
Leaf traits (written about or scanned and labeled)
```
```
Annual Recruitment and Mortality
# of trees (stems) in 2013 and 2018:
5-year mortality of trees (stems):
new tree recuitment:
max DBH in sample:
mean DBH in sample:
```
```
Graph of recruiment and mortality
{r echo=false}
hist()
```
```
Graph of species range and distribution
```
```
Graph of species range and distribution within the plot (plot location)
```
Picture of tree cores (with a small blurb)

### *Quercus falcata*	(Southern red oak)
```
Life history (information will be added by Michael)
```
```
Leaf traits (written about or scanned and labeled)
```
```
Annual Recruitment and Mortality
# of trees (stems) in 2013 and 2018:
5-year mortality of trees (stems):
new tree recuitment:
max DBH in sample:
mean DBH in sample:
```
```
Graph of recruiment and mortality
{r echo=false}
hist()
```
```
Graph of species range and distribution
```
```
Graph of species range and distribution within the plot (plot location)
```
Picture of tree cores (with a small blurb)

### *Quercus michauxii*	(Swamp chestnut oak)
```
Life history (information will be added by Michael)
```
```
Leaf traits (written about or scanned and labeled)
```
```
Annual Recruitment and Mortality
# of trees (stems) in 2013 and 2018:
5-year mortality of trees (stems):
new tree recuitment:
max DBH in sample:
mean DBH in sample:
```
```
Graph of recruiment and mortality
{r echo=false}
hist()
```
```
Graph of species range and distribution
```
```
Graph of species range and distribution within the plot (plot location)
```
Picture of tree cores (with a small blurb)

### *Quercus muehlenbergii*	(Chinkapin oak)
```
Life history (information will be added by Michael)
```
```
Leaf traits (written about or scanned and labeled)
```
```
Annual Recruitment and Mortality
# of trees (stems) in 2013 and 2018:
5-year mortality of trees (stems):
new tree recuitment:
max DBH in sample:
mean DBH in sample:
```
```
Graph of recruiment and mortality
{r echo=false}
hist()
```
```
Graph of species range and distribution
```
```
Graph of species range and distribution within the plot (plot location)
```
Picture of tree cores (with a small blurb)

### *Quercus prinus*	(Chestnut oak)
```
Life history (information will be added by Michael)
```
```
Leaf traits (written about or scanned and labeled)
```
```
Annual Recruitment and Mortality
# of trees (stems) in 2013 and 2018:
5-year mortality of trees (stems):
new tree recuitment:
max DBH in sample:
mean DBH in sample:
```
```
Graph of recruiment and mortality
{r echo=false}
hist()
```
```
Graph of species range and distribution
```
```
Graph of species range and distribution within the plot (plot location)
```
Picture of tree cores (with a small blurb)

### *Quercus rubra*	(Northern red oak)
```
Life history (information will be added by Michael)
```
```
Leaf traits (written about or scanned and labeled)
```
```
Annual Recruitment and Mortality
# of trees (stems) in 2013 and 2018:
5-year mortality of trees (stems):
new tree recuitment:
max DBH in sample:
mean DBH in sample:
```
```
Graph of recruiment and mortality
{r echo=false}
hist()
```
```
Graph of species range and distribution
```
```
Graph of species range and distribution within the plot (plot location)
```
Picture of tree cores (with a small blurb)

### *Quercus velutina*	(Black oak)
```
Life history (information will be added by Michael)
```
```
Leaf traits (written about or scanned and labeled)
```
```
Annual Recruitment and Mortality
# of trees (stems) in 2013 and 2018:
5-year mortality of trees (stems):
new tree recuitment:
max DBH in sample:
mean DBH in sample:
```
```
Graph of recruiment and mortality
{r echo=false}
hist()
```
```
Graph of species range and distribution
```
```
Graph of species range and distribution within the plot (plot location)
```
Picture of tree cores (with a small blurb)

## Hamamelidaceae
### *Hamamelis virginiana*	(American witchhazel)
```
Life history (information will be added by Michael)
```
```
Leaf traits (written about or scanned and labeled)
```
```
Annual Recruitment and Mortality
# of trees (stems) in 2013 and 2018:
5-year mortality of trees (stems):
new tree recuitment:
max DBH in sample:
mean DBH in sample:
```
```
Graph of recruiment and mortality
{r echo=false}
hist()
```
```
Graph of species range and distribution
```
```
Graph of species range and distribution within the plot (plot location)
```
Picture of tree cores (with a small blurb)

## Juglandaceae
### *Carya cordiformis*	(Bitternut hickory)
```
Life history (information will be added by Michael)
```
```
Leaf traits (written about or scanned and labeled)
```
```
Annual Recruitment and Mortality
# of trees (stems) in 2013 and 2018:
5-year mortality of trees (stems):
new tree recuitment:
max DBH in sample:
mean DBH in sample:
```
```
Graph of recruiment and mortality
{r echo=false}
hist()
```
```
Graph of species range and distribution
```
```
Graph of species range and distribution within the plot (plot location)
```
Picture of tree cores (with a small blurb)

### *Carya glabra* (Pignut hickory)
```
Life history (information will be added by Michael)
```
```
Leaf traits (written about or scanned and labeled)
```
```
Annual Recruitment and Mortality
# of trees (stems) in 2013 and 2018:
5-year mortality of trees (stems):
new tree recuitment:
max DBH in sample:
mean DBH in sample:
```
```
Graph of recruiment and mortality
{r echo=false}
hist()
```
```
Graph of species range and distribution
```
```
Graph of species range and distribution within the plot (plot location)
```
Picture of tree cores (with a small blurb)

### *Carya ovalis*	(Red hickory)
```
Life history (information will be added by Michael)
```
```
Leaf traits (written about or scanned and labeled)
```
```
Annual Recruitment and Mortality
# of trees (stems) in 2013 and 2018:
5-year mortality of trees (stems):
new tree recuitment:
max DBH in sample:
mean DBH in sample:
```
```
Graph of recruiment and mortality
{r echo=false}
hist()
```
```
Graph of species range and distribution
```
```
Graph of species range and distribution within the plot (plot location)
```
Picture of tree cores (with a small blurb)

### *Carya sp.*	(Hickory)
```
Life history (information will be added by Michael)
```
```
Leaf traits (written about or scanned and labeled)
```
```
Annual Recruitment and Mortality
# of trees (stems) in 2013 and 2018:
5-year mortality of trees (stems):
new tree recuitment:
max DBH in sample:
mean DBH in sample:
```
```
Graph of recruiment and mortality
{r echo=false}
hist()
```
```
Graph of species range and distribution
```
```
Graph of species range and distribution within the plot (plot location)
```
Picture of tree cores (with a small blurb)

### *Carya tomentosa*	(Mockernut hickory)
```
Life history (information will be added by Michael)
```
```
Leaf traits (written about or scanned and labeled)
```
```
Annual Recruitment and Mortality
# of trees (stems) in 2013 and 2018:
5-year mortality of trees (stems):
new tree recuitment:
max DBH in sample:
mean DBH in sample:
```
```
Graph of recruiment and mortality
{r echo=false}
hist()
```
```
Graph of species range and distribution
```
```
Graph of species range and distribution within the plot (plot location)
```
Picture of tree cores (with a small blurb)

### *Juglans cinerea*	(Butternut)
```
Life history (information will be added by Michael)
```
```
Leaf traits (written about or scanned and labeled)
```
```
Annual Recruitment and Mortality
# of trees (stems) in 2013 and 2018:
5-year mortality of trees (stems):
new tree recuitment:
max DBH in sample:
mean DBH in sample:
```
```
Graph of recruiment and mortality
{r echo=false}
hist()
```
```
Graph of species range and distribution
```
```
Graph of species range and distribution within the plot (plot location)
```
Picture of tree cores (with a small blurb)

### *Juglans nigra*	(Black walnut)
```
Life history (information will be added by Michael)
```
```
Leaf traits (written about or scanned and labeled)
```
```
Annual Recruitment and Mortality
# of trees (stems) in 2013 and 2018:
5-year mortality of trees (stems):
new tree recuitment:
max DBH in sample:
mean DBH in sample:
```
```
Graph of recruiment and mortality
{r echo=false}
hist()
```
```
Graph of species range and distribution
```
```
Graph of species range and distribution within the plot (plot location)
```
Picture of tree cores (with a small blurb)

## Lauraceae
### *Lindera benzoin*	(Spicebush)
```
Life history (information will be added by Michael)
```
```
Leaf traits (written about or scanned and labeled)
```
```
Annual Recruitment and Mortality
# of trees (stems) in 2013 and 2018:
5-year mortality of trees (stems):
new tree recuitment:
max DBH in sample:
mean DBH in sample:
```
```
Graph of recruiment and mortality
{r echo=false}
hist()
```
```
Graph of species range and distribution
```
```
Graph of species range and distribution within the plot (plot location)
```
Picture of tree cores (with a small blurb)

### *Sassafras albidum* (Sassafras)
```
Life history (information will be added by Michael)
```
```
Leaf traits (written about or scanned and labeled)
```
```
Annual Recruitment and Mortality
# of trees (stems) in 2013 and 2018:
5-year mortality of trees (stems):
new tree recuitment:
max DBH in sample:
mean DBH in sample:
```
```
Graph of recruiment and mortality
{r echo=false}
hist()
```
```
Graph of species range and distribution
```
```
Graph of species range and distribution within the plot (plot location)
```
Picture of tree cores (with a small blurb)

## Magnoliaceae
### *Liriodendron tulipifera*	(Tulip poplar)
```
Life history (information will be added by Michael)
```
```
Leaf traits (written about or scanned and labeled)
```
```
Annual Recruitment and Mortality
# of trees (stems) in 2013 and 2018:
5-year mortality of trees (stems):
new tree recuitment:
max DBH in sample:
mean DBH in sample:
```
```
Graph of recruiment and mortality
{r echo=false}
hist()
```
```
Graph of species range and distribution
```
```
Graph of species range and distribution within the plot (plot location)
```
Picture of tree cores (with a small blurb)
## Malvaceae
### *Tilia americana*	(American basswood)
```
Life history (information will be added by Michael)
```
```
Leaf traits (written about or scanned and labeled)
```
```
Annual Recruitment and Mortality
# of trees (stems) in 2013 and 2018:
5-year mortality of trees (stems):
new tree recuitment:
max DBH in sample:
mean DBH in sample:
```
```
Graph of recruiment and mortality
{r echo=false}
hist()
```
```
Graph of species range and distribution
```
```
Graph of species range and distribution within the plot (plot location)
```
Picture of tree cores (with a small blurb)

## Nyssaceae
### *Nyssa sylvatica*	(Black gum)
```
Life history (information will be added by Michael)
```
```
Leaf traits (written about or scanned and labeled)
```
```
Annual Recruitment and Mortality
# of trees (stems) in 2013 and 2018:
5-year mortality of trees (stems):
new tree recuitment:
max DBH in sample:
mean DBH in sample:
```
```
Graph of recruiment and mortality
{r echo=false}
hist()
```
```
Graph of species range and distribution
```
```
Graph of species range and distribution within the plot (plot location)
```
Picture of tree cores (with a small blurb)

## Oleaceae
### *Chionanthus virginicus*	(Fringe tree)
```
Life history (information will be added by Michael)
```
```
Leaf traits (written about or scanned and labeled)
```
```
Annual Recruitment and Mortality
# of trees (stems) in 2013 and 2018:
5-year mortality of trees (stems):
new tree recuitment:
max DBH in sample:
mean DBH in sample:
```
```
Graph of recruiment and mortality
{r echo=false}
hist()
```
```
Graph of species range and distribution
```
```
Graph of species range and distribution within the plot (plot location)
```
Picture of tree cores (with a small blurb)

### *Fraxinus americana* (White ash)
```
Life history (information will be added by Michael)
```
```
Leaf traits (written about or scanned and labeled)
```
```
Annual Recruitment and Mortality
# of trees (stems) in 2013 and 2018:
5-year mortality of trees (stems):
new tree recuitment:
max DBH in sample:
mean DBH in sample:
```
```
Graph of recruiment and mortality
{r echo=false}
hist()
```
```
Graph of species range and distribution
```
```
Graph of species range and distribution within the plot (plot location)
```
Picture of tree cores (with a small blurb)

### *Fraxinus nigra*	(Black ash)
```
Life history (information will be added by Michael)
```
```
Leaf traits (written about or scanned and labeled)
```
```
Annual Recruitment and Mortality
# of trees (stems) in 2013 and 2018:
5-year mortality of trees (stems):
new tree recuitment:
max DBH in sample:
mean DBH in sample:
```
```
Graph of recruiment and mortality
{r echo=false}
hist()
```
```
Graph of species range and distribution
```
```
Graph of species range and distribution within the plot (plot location)
```
Picture of tree cores (with a small blurb)

### *Fraxinus pennsylvanica*	(Green ash)
```
Life history (information will be added by Michael)
```
```
Leaf traits (written about or scanned and labeled)
```
```
Annual Recruitment and Mortality
# of trees (stems) in 2013 and 2018:
5-year mortality of trees (stems):
new tree recuitment:
max DBH in sample:
mean DBH in sample:
```
```
Graph of recruiment and mortality
{r echo=false}
hist()
```
```
Graph of species range and distribution
```
```
Graph of species range and distribution within the plot (plot location)
```
Picture of tree cores (with a small blurb)

## Paulowniaceae
### *Paulownia tomentosa*	(Princess tree)
```
Life history (information will be added by Michael)
```
```
Leaf traits (written about or scanned and labeled)
```
```
Annual Recruitment and Mortality
# of trees (stems) in 2013 and 2018:
5-year mortality of trees (stems):
new tree recuitment:
max DBH in sample:
mean DBH in sample:
```
```
Graph of recruiment and mortality
{r echo=false}
hist()
```
```
Graph of species range and distribution
```
```
Graph of species range and distribution within the plot (plot location)
```
Picture of tree cores (with a small blurb)

## Pinaceae
### *Pinus pungens*	(Table mountain pine)
```
Life history (information will be added by Michael)
```
```
Leaf traits (written about or scanned and labeled)
```
```
Annual Recruitment and Mortality
# of trees (stems) in 2013 and 2018:
5-year mortality of trees (stems):
new tree recuitment:
max DBH in sample:
mean DBH in sample:
```
```
Graph of recruiment and mortality
{r echo=false}
hist()
```
```
Graph of species range and distribution
```
```
Graph of species range and distribution within the plot (plot location)
```
Picture of tree cores (with a small blurb)

### *Pinus strobus*	(White pine)
```
Life history (information will be added by Michael)
```
```
Leaf traits (written about or scanned and labeled)
```
```
Annual Recruitment and Mortality
# of trees (stems) in 2013 and 2018:
5-year mortality of trees (stems):
new tree recuitment:
max DBH in sample:
mean DBH in sample:
```
```
Graph of recruiment and mortality
{r echo=false}
hist()
```
```
Graph of species range and distribution
```
```
Graph of species range and distribution within the plot (plot location)
```
Picture of tree cores (with a small blurb)

### *Pinus virginiana*	(Virginia pine)
```
Life history (information will be added by Michael)
```
```
Leaf traits (written about or scanned and labeled)
```
```
Annual Recruitment and Mortality
# of trees (stems) in 2013 and 2018:
5-year mortality of trees (stems):
new tree recuitment:
max DBH in sample:
mean DBH in sample:
```
```
Graph of recruiment and mortality
{r echo=false}
hist()
```
```
Graph of species range and distribution
```
```
Graph of species range and distribution within the plot (plot location)
```
Picture of tree cores (with a small blurb)

## Platanaceae
### *Platanus occidentalis*	(American sycamore)
```
Life history (information will be added by Michael)
```
```
Leaf traits (written about or scanned and labeled)
```
```
Annual Recruitment and Mortality
# of trees (stems) in 2013 and 2018:
5-year mortality of trees (stems):
new tree recuitment:
max DBH in sample:
mean DBH in sample:
```
```
Graph of recruiment and mortality
{r echo=false}
hist()
```
```
Graph of species range and distribution
```
```
Graph of species range and distribution within the plot (plot location)
```
Picture of tree cores (with a small blurb)

## Rosaceae
### *Amelanchier arborea*	(Downy serviceberry)
```
Life history (information will be added by Michael)
```
```
Leaf traits (written about or scanned and labeled)
```
```
Annual Recruitment and Mortality
# of trees (stems) in 2013 and 2018:
5-year mortality of trees (stems):
new tree recuitment:
max DBH in sample:
mean DBH in sample:
```
```
Graph of recruiment and mortality
{r echo=false}
hist()
```
```
Graph of species range and distribution
```
```
Graph of species range and distribution within the plot (plot location)
```
Picture of tree cores (with a small blurb)

### *Crataegus pruniosa*	(Waxyfruit hawthorn)
```
Life history (information will be added by Michael)
```
```
Leaf traits (written about or scanned and labeled)
```
```
Annual Recruitment and Mortality
# of trees (stems) in 2013 and 2018:
5-year mortality of trees (stems):
new tree recuitment:
max DBH in sample:
mean DBH in sample:
```
```
Graph of recruiment and mortality
{r echo=false}
hist()
```
```
Graph of species range and distribution
```
```
Graph of species range and distribution within the plot (plot location)
```
Picture of tree cores (with a small blurb)

### *Prunus avium*	(Sweet cherry)
```
Life history (information will be added by Michael)
```
```
Leaf traits (written about or scanned and labeled)
```
```
Annual Recruitment and Mortality
# of trees (stems) in 2013 and 2018:
5-year mortality of trees (stems):
new tree recuitment:
max DBH in sample:
mean DBH in sample:
```
```
Graph of recruiment and mortality
{r echo=false}
hist()
```
```
Graph of species range and distribution
```
```
Graph of species range and distribution within the plot (plot location)
```
Picture of tree cores (with a small blurb)

### *Prunus persica*	(Peach)
```
Life history (information will be added by Michael)
```
```
Leaf traits (written about or scanned and labeled)
```
```
Annual Recruitment and Mortality
# of trees (stems) in 2013 and 2018:
5-year mortality of trees (stems):
new tree recuitment:
max DBH in sample:
mean DBH in sample:
```
```
Graph of recruiment and mortality
{r echo=false}
hist()
```
```
Graph of species range and distribution
```
```
Graph of species range and distribution within the plot (plot location)
```
Picture of tree cores (with a small blurb)

### *Prunus serotina*	(Wild black cherry)
```
Life history (information will be added by Michael)
```
```
Leaf traits (written about or scanned and labeled)
```
```
Annual Recruitment and Mortality
# of trees (stems) in 2013 and 2018:
5-year mortality of trees (stems):
new tree recuitment:
max DBH in sample:
mean DBH in sample:
```
```
Graph of recruiment and mortality
{r echo=false}
hist()
```
```
Graph of species range and distribution
```
```
Graph of species range and distribution within the plot (plot location)
```
Picture of tree cores (with a small blurb)

### *Rosa multiflora*	(Multiflora rose)
```
Life history (information will be added by Michael)
```
```
Leaf traits (written about or scanned and labeled)
```
```
Annual Recruitment and Mortality
# of trees (stems) in 2013 and 2018:
5-year mortality of trees (stems):
new tree recuitment:
max DBH in sample:
mean DBH in sample:
```
```
Graph of recruiment and mortality
{r echo=false}
hist()
```
```
Graph of species range and distribution
```
```
Graph of species range and distribution within the plot (plot location)
```
Picture of tree cores (with a small blurb)

### *Rubus allegheniensis* (Allegheny blackberry)
```
Life history (information will be added by Michael)
```
```
Leaf traits (written about or scanned and labeled)
```
```
Annual Recruitment and Mortality
# of trees (stems) in 2013 and 2018:
5-year mortality of trees (stems):
new tree recuitment:
max DBH in sample:
mean DBH in sample:
```
```
Graph of recruiment and mortality
{r echo=false}
hist()
```
```
Graph of species range and distribution
```
```
Graph of species range and distribution within the plot (plot location)
```
Picture of tree cores (with a small blurb)

### *Rubus pensilvanicus*	(Pennsylvania blackberry)
```
Life history (information will be added by Michael)
```
```
Leaf traits (written about or scanned and labeled)
```
```
Annual Recruitment and Mortality
# of trees (stems) in 2013 and 2018:
5-year mortality of trees (stems):
new tree recuitment:
max DBH in sample:
mean DBH in sample:
```
```
Graph of recruiment and mortality
{r echo=false}
hist()
```
```
Graph of species range and distribution
```
```
Graph of species range and distribution within the plot (plot location)
```
Picture of tree cores (with a small blurb)

*Rubus phoenicolasius*	(Wineberry)
```
Life history (information will be added by Michael)
```
```
Leaf traits (written about or scanned and labeled)
```
```
Annual Recruitment and Mortality
# of trees (stems) in 2013 and 2018:
5-year mortality of trees (stems):
new tree recuitment:
max DBH in sample:
mean DBH in sample:
```
```
Graph of recruiment and mortality
{r echo=false}
hist()
```
```
Graph of species range and distribution
```
```
Graph of species range and distribution within the plot (plot location)
```
Picture of tree cores (with a small blurb)

## Sapindaceae
### *Acer negundo* (Boxelder)
```
Life history (information will be added by Michael)
```
```
Leaf traits (written about or scanned and labeled)
```
```
Annual Recruitment and Mortality
# of trees (stems) in 2013 and 2018:
5-year mortality of trees (stems):
new tree recuitment:
max DBH in sample:
mean DBH in sample:
```
```
Graph of recruiment and mortality
{r echo=false}
hist()
```
```
Graph of species range and distribution
```
```
Graph of species range and distribution within the plot (plot location)
```
Picture of tree cores (with a small blurb)

### *Acer platanoides*	(Norway maple)
```
Life history (information will be added by Michael)
```
```
Leaf traits (written about or scanned and labeled)
```
```
Annual Recruitment and Mortality
# of trees (stems) in 2013 and 2018:
5-year mortality of trees (stems):
new tree recuitment:
max DBH in sample:
mean DBH in sample:
```
```
Graph of recruiment and mortality
{r echo=false}
hist()
```
```
Graph of species range and distribution
```
```
Graph of species range and distribution within the plot (plot location)
```
Picture of tree cores (with a small blurb)

### *Acer rubrum*	(Red maple)
```
Life history (information will be added by Michael)
```
```
Leaf traits (written about or scanned and labeled)
```
```
Annual Recruitment and Mortality
# of trees (stems) in 2013 and 2018:
5-year mortality of trees (stems):
new tree recuitment:
max DBH in sample:
mean DBH in sample:
```
```
Graph of recruiment and mortality
{r echo=false}
hist()
```
```
Graph of species range and distribution
```
```
Graph of species range and distribution within the plot (plot location)
```
Picture of tree cores (with a small blurb)

## Simaroubaceae
### *Ailanthus altissima*	(Tree of heaven)
```
Life history (information will be added by Michael)
```
```
Leaf traits (written about or scanned and labeled)
```
```
Annual Recruitment and Mortality
# of trees (stems) in 2013 and 2018:
5-year mortality of trees (stems):
new tree recuitment:
max DBH in sample:
mean DBH in sample:
```
```
Graph of recruiment and mortality
{r echo=false}
hist()
```
```
Graph of species range and distribution
```
```
Graph of species range and distribution within the plot (plot location)
```
Picture of tree cores (with a small blurb)

## Ulmaceae
### *Ulmus americana*	(American elm)
```
Life history (information will be added by Michael)
```
```
Leaf traits (written about or scanned and labeled)
```
```
Annual Recruitment and Mortality
# of trees (stems) in 2013 and 2018:
5-year mortality of trees (stems):
new tree recuitment:
max DBH in sample:
mean DBH in sample:
```
```
Graph of recruiment and mortality
{r echo=false}
hist()
```
```
Graph of species range and distribution
```
```
Graph of species range and distribution within the plot (plot location)
```
Picture of tree cores (with a small blurb)

### *Ulmus rubra*	(Slippery elm)
```
Life history (information will be added by Michael)
```
```
Leaf traits (written about or scanned and labeled)
```
```
Annual Recruitment and Mortality
# of trees (stems) in 2013 and 2018:
5-year mortality of trees (stems):
new tree recuitment:
max DBH in sample:
mean DBH in sample:
```
```
Graph of recruiment and mortality
{r echo=false}
hist()
```
```
Graph of species range and distribution
```
```
Graph of species range and distribution within the plot (plot location)
```
Picture of tree cores (with a small blurb)
