# Woody Plants
For life history, mention common canopy positions
  - information from Ramage et al. 2017
    - dominant canopy are *Liriondendron tulipifera* (tulip poplar), *Carya* spp., *Quercus* spp., *Fraxinus americana* (white ash), *Nyssa sylvatica* (black gum)

##Adoxaceae
### *Sambucus canadensis* (L.) R. Bolli ```American Black Elderberry```
```
Life history (information will be added by Michael)
```
```
Leaf traits (written about or scanned and labeled)
```
```
Annual Recruitment and Mortality
# of trees (stems) in 2013 and 2018:
5-year mortality of trees (stems):
new tree recuitment:
max DBH in sample:
mean DBH in sample:
```
```
Graph of recruiment and mortality
{r echo=false}
hist()
```
```
Graph of species range and distribution
```
```
Graph of species range and distribution within the plot (plot location)
```
Picture of tree cores (with a small blurb)

### *Viburnum acerifolium* L. ```Mapleleaf Viburnum```
```
Life history (information will be added by Michael)
```
```
Leaf traits (written about or scanned and labeled)
```
```
Annual Recruitment and Mortality
# of trees (stems) in 2013 and 2018:
5-year mortality of trees (stems):
new tree recuitment:
max DBH in sample:
mean DBH in sample:
```
```
Graph of recruiment and mortality
{r echo=false}
hist()
```
```
Graph of species range and distribution
```
```
Graph of species range and distribution within the plot (plot location)
```
Picture of tree cores (with a small blurb)

###	*Viburnum prunifolium* L. ```Black Haw```
```
Life history (information will be added by Michael)
```
```
Leaf traits (written about or scanned and labeled)
```
```
Annual Recruitment and Mortality
# of trees (stems) in 2013 and 2018:
5-year mortality of trees (stems):
new tree recuitment:
max DBH in sample:
mean DBH in sample:
```
```
Graph of recruiment and mortality
{r echo=false}
hist()
```
```
Graph of species range and distribution
```
```
Graph of species range and distribution within the plot (plot location)
```
Picture of tree cores (with a small blurb)

###	*Viburnum recognitum* Fernald ```Southern Arrow-wood```
```
Life history (information will be added by Michael)
***also known as *Virburnum dentatum* L.***
```
```
Leaf traits (written about or scanned and labeled)
```
```
Annual Recruitment and Mortality
# of trees (stems) in 2013 and 2018:
5-year mortality of trees (stems):
new tree recuitment:
max DBH in sample:
mean DBH in sample:
```
```
Graph of recruiment and mortality
{r echo=false}
hist()
```
```
Graph of species range and distribution
```
```
Graph of species range and distribution within the plot (plot location)
```
Picture of tree cores (with a small blurb)

## Annonaceae
### *Asimina triloba*	(L.) Dunal ```Pawpaw```
```
Life history (information will be added by Michael)
```
```
Leaf traits (written about or scanned and labeled)
```
```
Annual Recruitment and Mortality
# of trees (stems) in 2013 and 2018:
5-year mortality of trees (stems):
new tree recuitment:
max DBH in sample:
mean DBH in sample:
```
```
Graph of recruiment and mortality
{r echo=false}
hist()
```
```
Graph of species range and distribution
```
```
Graph of species range and distribution within the plot (plot location)
```
Picture of tree cores (with a small blurb)

##Aquifoliaceae
### *Ilex verticillata* (L.) A. Gray ```Common Winterberry```
```
Life history (information will be added by Michael)
```
```
Leaf traits (written about or scanned and labeled)
```
```
Annual Recruitment and Mortality
# of trees (stems) in 2013 and 2018:
5-year mortality of trees (stems):
new tree recuitment:
max DBH in sample:
mean DBH in sample:
```
```
Graph of recruiment and mortality
{r echo=false}
hist()
```
```
Graph of species range and distribution
```
```
Graph of species range and distribution within the plot (plot location)
```
Picture of tree cores (with a small blurb)

##Berberidaceae
### *Berberis thunbergii* DC. ```Japanese Barberry```
```
Life history (information will be added by Michael)
```
```
Leaf traits (written about or scanned and labeled)
```
```
Annual Recruitment and Mortality
# of trees (stems) in 2013 and 2018:
5-year mortality of trees (stems):
new tree recuitment:
max DBH in sample:
mean DBH in sample:
```
```
Graph of recruiment and mortality
{r echo=false}
hist()
```
```
Graph of species range and distribution
```
```
Graph of species range and distribution within the plot (plot location)
```
Picture of tree cores (with a small blurb)

## Betulaceae
### *Carpinus caroliniana* Walt. ```American Hornbeam```
```
Life history (information will be added by Michael)
```
```
Leaf traits (written about or scanned and labeled)
```
```
Annual Recruitment and Mortality
# of trees (stems) in 2013 and 2018:
5-year mortality of trees (stems):
new tree recuitment:
max DBH in sample:
mean DBH in sample:
```
```
Graph of recruiment and mortality
{r echo=false}
hist()
```
```
Graph of species range and distribution
```
```
Graph of species range and distribution within the plot (plot location)
```
Picture of tree cores (with a small blurb)

###	*Corylus americana*	Walt. ```American Hazelnut```
```
Life history (information will be added by Michael)
```
```
Leaf traits (written about or scanned and labeled)
```
```
Annual Recruitment and Mortality
# of trees (stems) in 2013 and 2018:
5-year mortality of trees (stems):
new tree recuitment:
max DBH in sample:
mean DBH in sample:
```
```
Graph of recruiment and mortality
{r echo=false}
hist()
```
```
Graph of species range and distribution
```
```
Graph of species range and distribution within the plot (plot location)
```
Picture of tree cores (with a small blurb)

## Cannabaceae
### *Celtis occidentalis*	L. ```Hackberry```
```
Life history (information will be added by Michael)
```
```
Leaf traits (written about or scanned and labeled)
```
```
Annual Recruitment and Mortality
# of trees (stems) in 2013 and 2018:
5-year mortality of trees (stems):
new tree recuitment:
max DBH in sample:
mean DBH in sample:
```
```
Graph of recruiment and mortality
{r echo=false}
hist()
```
```
Graph of species range and distribution
```
```
Graph of species range and distribution within the plot (plot location)
```
Picture of tree cores (with a small blurb)

## Caprifoliaceae
### *Lonicera maackii* (Rupr.) Maxim ```Bush Honeysuckle```
```
Life history (information will be added by Michael)
```
```
Leaf traits (written about or scanned and labeled)
```
```
Annual Recruitment and Mortality
# of trees (stems) in 2013 and 2018:
5-year mortality of trees (stems):
new tree recuitment:
max DBH in sample:
mean DBH in sample:
```
```
Graph of recruiment and mortality
{r echo=false}
hist()
```
```
Graph of species range and distribution
```
```
Graph of species range and distribution within the plot (plot location)
```
Picture of tree cores (with a small blurb)

## Celastracea
### *Euonymus alatus* (Thunb.) Sieb. ```Burning Bush```
```
Life history (information will be added by Michael)
**Species is also known as Winged Euonymus.**
```
```
Leaf traits (written about or scanned and labeled)
```
```
Annual Recruitment and Mortality
# of trees (stems) in 2013 and 2018:
5-year mortality of trees (stems):
new tree recuitment:
max DBH in sample:
mean DBH in sample:
```
```
Graph of recruiment and mortality
{r echo=false}
hist()
```
```
Graph of species range and distribution
```
```
Graph of species range and distribution within the plot (plot location)
```
Picture of tree cores (with a small blurb)

## Cornaceae
### *Cornus alternifolia*	L. f. ```Alternate Leaf Dogwood```
```
Life history (information will be added by Michael)
```
```
Leaf traits (written about or scanned and labeled)
```
```
Annual Recruitment and Mortality
# of trees (stems) in 2013 and 2018:
5-year mortality of trees (stems):
new tree recuitment:
max DBH in sample:
mean DBH in sample:
```
```
Graph of recruiment and mortality
{r echo=false}
hist()
```
```
Graph of species range and distribution
```
```
Graph of species range and distribution within the plot (plot location)
```
Picture of tree cores (with a small blurb)

### *Cornus florida* L. ```Flowering Dogwood```
```
Life history (information will be added by Michael)
```
```
Leaf traits (written about or scanned and labeled)
```
```
Annual Recruitment and Mortality
# of trees (stems) in 2013 and 2018:
5-year mortality of trees (stems):
new tree recuitment:
max DBH in sample:
mean DBH in sample:
```
```
Graph of recruiment and mortality
{r echo=false}
hist()
```
```
Graph of species range and distribution
```
```
Graph of species range and distribution within the plot (plot location)
```
Picture of tree cores (with a small blurb)

## Ebenaceae
### *Diospyros virginiana* L. ```Persimmon```
```
Life history (information will be added by Michael)
```
```
Leaf traits (written about or scanned and labeled)
```
```
Annual Recruitment and Mortality
# of trees (stems) in 2013 and 2018:
5-year mortality of trees (stems):
new tree recuitment:
max DBH in sample:
mean DBH in sample:
```
```
Graph of recruiment and mortality
{r echo=false}
hist()
```
```
Graph of species range and distribution
```
```
Graph of species range and distribution within the plot (plot location)
```
Picture of tree cores (with a small blurb)

## Elaeagnaceae
### *Elaeagnus umbellata*	Thunb. ```Autumn Olive```
```
Life history (information will be added by Michael)
```
```
Leaf traits (written about or scanned and labeled)
```
```
Annual Recruitment and Mortality
# of trees (stems) in 2013 and 2018:
5-year mortality of trees (stems):
new tree recuitment:
max DBH in sample:
mean DBH in sample:
```
```
Graph of recruiment and mortality
{r echo=false}
hist()
```
```
Graph of species range and distribution
```
```
Graph of species range and distribution within the plot (plot location)
```
Picture of tree cores (with a small blurb)

## Fabaceae
### *Cercis canadensis* L. ```Eastern Redbud```
```
Life history (information will be added by Michael)
```
```
Leaf traits (written about or scanned and labeled)
```
```
Annual Recruitment and Mortality
# of trees (stems) in 2013 and 2018:
5-year mortality of trees (stems):
new tree recuitment:
max DBH in sample:
mean DBH in sample:
```
```
Graph of recruiment and mortality
{r echo=false}
hist()
```
```
Graph of species range and distribution
```
```
Graph of species range and distribution within the plot (plot location)
```
Picture of tree cores (with a small blurb)

### *Robinia pseudoacacia* L. ```Black Locust```
```
Life history (information will be added by Michael)
```
```
Leaf traits (written about or scanned and labeled)
```
```
Annual Recruitment and Mortality
# of trees (stems) in 2013 and 2018:
5-year mortality of trees (stems):
new tree recuitment:
max DBH in sample:
mean DBH in sample:
```
```
Graph of recruiment and mortality
{r echo=false}
hist()
```
```
Graph of species range and distribution
```
```
Graph of species range and distribution within the plot (plot location)
```
Picture of tree cores (with a small blurb)

## Fagaceae
### *Castanea dentata* (Marsh.) Borkh. ```American Chestnut```
```
Life history (information will be added by Michael)
```
```
Leaf traits (written about or scanned and labeled)
```
```
Annual Recruitment and Mortality
# of trees (stems) in 2013 and 2018:
5-year mortality of trees (stems):
new tree recuitment:
max DBH in sample:
mean DBH in sample:
```
```
Graph of recruiment and mortality
{r echo=false}
hist()
```
```
Graph of species range and distribution
```
```
Graph of species range and distribution within the plot (plot location)
```
Picture of tree cores (with a small blurb)

### *Fagus grandifolia*	Ehrh. ```American Beech```
```
Life history (information will be added by Michael)
```
```
Leaf traits (written about or scanned and labeled)
```
```
Annual Recruitment and Mortality
# of trees (stems) in 2013 and 2018:
5-year mortality of trees (stems):
new tree recuitment:
max DBH in sample:
mean DBH in sample:
```
```
Graph of recruiment and mortality
{r echo=false}
hist()
```
```
Graph of species range and distribution
```
```
Graph of species range and distribution within the plot (plot location)
```
Picture of tree cores (with a small blurb)

### *Quercus alba* L. ```White Oak```
```
Life history (information will be added by Michael)
```
```
Leaf traits (written about or scanned and labeled)
```
```
Annual Recruitment and Mortality
# of trees (stems) in 2013 and 2018:
5-year mortality of trees (stems):
new tree recuitment:
max DBH in sample:
mean DBH in sample:
```
```
Graph of recruiment and mortality
{r echo=false}
hist()
```
```
Graph of species range and distribution
```
```
Graph of species range and distribution within the plot (plot location)
```
Picture of tree cores (with a small blurb)

### *Quercus coccinea* Muenchh. ```Scarlet Oak```
```
Life history (information will be added by Michael)
```
```
Leaf traits (written about or scanned and labeled)
```
```
Annual Recruitment and Mortality
# of trees (stems) in 2013 and 2018:
5-year mortality of trees (stems):
new tree recuitment:
max DBH in sample:
mean DBH in sample:
```
```
Graph of recruiment and mortality
{r echo=false}
hist()
```
```
Graph of species range and distribution
```
```
Graph of species range and distribution within the plot (plot location)
```
Picture of tree cores (with a small blurb)

### *Quercus falcata* Michx. ```Southern Red Oak```
```
Life history (information will be added by Michael)
```
```
Leaf traits (written about or scanned and labeled)
```
```
Annual Recruitment and Mortality
# of trees (stems) in 2013 and 2018:
5-year mortality of trees (stems):
new tree recuitment:
max DBH in sample:
mean DBH in sample:
```
```
Graph of recruiment and mortality
{r echo=false}
hist()
```
```
Graph of species range and distribution
```
```
Graph of species range and distribution within the plot (plot location)
```
Picture of tree cores (with a small blurb)

### *Quercus michauxii* Nutt. ```Swamp Chestnut Oak```
```
Life history (information will be added by Michael)
```
```
Leaf traits (written about or scanned and labeled)
```
```
Annual Recruitment and Mortality
# of trees (stems) in 2013 and 2018:
5-year mortality of trees (stems):
new tree recuitment:
max DBH in sample:
mean DBH in sample:
```
```
Graph of recruiment and mortality
{r echo=false}
hist()
```
```
Graph of species range and distribution
```
```
Graph of species range and distribution within the plot (plot location)
```
Picture of tree cores (with a small blurb)

### *Quercus muehlenbergii* Engelm. ```Chinkapin Oak```
```
Life history (information will be added by Michael)
```
```
Leaf traits (written about or scanned and labeled)
```
```
Annual Recruitment and Mortality
# of trees (stems) in 2013 and 2018:
5-year mortality of trees (stems):
new tree recuitment:
max DBH in sample:
mean DBH in sample:
```
```
Graph of recruiment and mortality
{r echo=false}
hist()
```
```
Graph of species range and distribution
```
```
Graph of species range and distribution within the plot (plot location)
```
Picture of tree cores (with a small blurb)

### *Quercus montana* Willd. ```Chestnut Oak```
**Formally known as *Quercus prinus* L.**
```
Life history (information will be added by Michael)
```
```
Leaf traits (written about or scanned and labeled)
```
```
Annual Recruitment and Mortality
# of trees (stems) in 2013 and 2018:
5-year mortality of trees (stems):
new tree recuitment:
max DBH in sample:
mean DBH in sample:
```
```
Graph of recruiment and mortality
{r echo=false}
hist()
```
```
Graph of species range and distribution
```
```
Graph of species range and distribution within the plot (plot location)
```
Picture of tree cores (with a small blurb)

### *Quercus rubra*	L. ```Northern Red Oak```
```
Life history (information will be added by Michael)
```
```
Leaf traits (written about or scanned and labeled)
```
```
Annual Recruitment and Mortality
# of trees (stems) in 2013 and 2018:
5-year mortality of trees (stems):
new tree recuitment:
max DBH in sample:
mean DBH in sample:
```
```
Graph of recruiment and mortality
{r echo=false}
hist()
```
```
Graph of species range and distribution
```
```
Graph of species range and distribution within the plot (plot location)
```
Picture of tree cores (with a small blurb)

### *Quercus velutina* Lam.	```Black Oak```
```
Life history (information will be added by Michael)
```
```
Leaf traits (written about or scanned and labeled)
```
```
Annual Recruitment and Mortality
# of trees (stems) in 2013 and 2018:
5-year mortality of trees (stems):
new tree recuitment:
max DBH in sample:
mean DBH in sample:
```
```
Graph of recruiment and mortality
{r echo=false}
hist()
```
```
Graph of species range and distribution
```
```
Graph of species range and distribution within the plot (plot location)
```
Picture of tree cores (with a small blurb)

## Hamamelidaceae
### *Hamamelis virginiana* L. var. virginiana	```Witch Hazel```
```
Life history (information will be added by Michael)
```
```
Leaf traits (written about or scanned and labeled)
```
```
Annual Recruitment and Mortality
# of trees (stems) in 2013 and 2018:
5-year mortality of trees (stems):
new tree recuitment:
max DBH in sample:
mean DBH in sample:
```
```
Graph of recruiment and mortality
{r echo=false}
hist()
```
```
Graph of species range and distribution
```
```
Graph of species range and distribution within the plot (plot location)
```
Picture of tree cores (with a small blurb)

## Juglandaceae
### *Carya cordiformis* (Wangenh.) K. Koch	```Bitternut Hickory```
```
Life history (information will be added by Michael)
```
```
Leaf traits (written about or scanned and labeled)
```
```
Annual Recruitment and Mortality
# of trees (stems) in 2013 and 2018:
5-year mortality of trees (stems):
new tree recuitment:
max DBH in sample:
mean DBH in sample:
```
```
Graph of recruiment and mortality
{r echo=false}
hist()
```
```
Graph of species range and distribution
```
```
Graph of species range and distribution within the plot (plot location)
```
Picture of tree cores (with a small blurb)

### *Carya glabra* (P. Mill.) ```Pignut Hickory```
```
Life history (information will be added by Michael)
```
```
Leaf traits (written about or scanned and labeled)
```
```
Annual Recruitment and Mortality
# of trees (stems) in 2013 and 2018:
5-year mortality of trees (stems):
new tree recuitment:
max DBH in sample:
mean DBH in sample:
```
```
Graph of recruiment and mortality
{r echo=false}
hist()
```
```
Graph of species range and distribution
```
```
Graph of species range and distribution within the plot (plot location)
```
Picture of tree cores (with a small blurb)

### *Carya ovalis* (Wangenh.) Sarg.	```Red Hickory```
```
Life history (information will be added by Michael)
```
```
Leaf traits (written about or scanned and labeled)
```
```
Annual Recruitment and Mortality
# of trees (stems) in 2013 and 2018:
5-year mortality of trees (stems):
new tree recuitment:
max DBH in sample:
mean DBH in sample:
```
```
Graph of recruiment and mortality
{r echo=false}
hist()
```
```
Graph of species range and distribution
```
```
Graph of species range and distribution within the plot (plot location)
```
Picture of tree cores (with a small blurb)

### *Carya tomentosa* (Lam. ex Pior.) Nutt.	```Mockernut Hickory```
```
Life history (information will be added by Michael)
```
```
Leaf traits (written about or scanned and labeled)
```
```
Annual Recruitment and Mortality
# of trees (stems) in 2013 and 2018:
5-year mortality of trees (stems):
new tree recuitment:
max DBH in sample:
mean DBH in sample:
```
```
Graph of recruiment and mortality
{r echo=false}
hist()
```
```
Graph of species range and distribution
```
```
Graph of species range and distribution within the plot (plot location)
```
Picture of tree cores (with a small blurb)

### *Juglans cinerea* L. ```Butternut```
```
Life history (information will be added by Michael)
```
```
Leaf traits (written about or scanned and labeled)
```
```
Annual Recruitment and Mortality
# of trees (stems) in 2013 and 2018:
5-year mortality of trees (stems):
new tree recuitment:
max DBH in sample:
mean DBH in sample:
```
```
Graph of recruiment and mortality
{r echo=false}
hist()
```
```
Graph of species range and distribution
```
```
Graph of species range and distribution within the plot (plot location)
```
Picture of tree cores (with a small blurb)

### *Juglans nigra*	L. ```Black Walnut```
```
Life history (information will be added by Michael)
```
```
Leaf traits (written about or scanned and labeled)
```
```
Annual Recruitment and Mortality
# of trees (stems) in 2013 and 2018:
5-year mortality of trees (stems):
new tree recuitment:
max DBH in sample:
mean DBH in sample:
```
```
Graph of recruiment and mortality
{r echo=false}
hist()
```
```
Graph of species range and distribution
```
```
Graph of species range and distribution within the plot (plot location)
```
Picture of tree cores (with a small blurb)

## Lauraceae
### *Lindera benzoin* (L.) Blume	```Spicebush```
```
Life history (information will be added by Michael)
```
```
Leaf traits (written about or scanned and labeled)
```
```
Annual Recruitment and Mortality
# of trees (stems) in 2013 and 2018:
5-year mortality of trees (stems):
new tree recuitment:
max DBH in sample:
mean DBH in sample:
```
```
Graph of recruiment and mortality
{r echo=false}
hist()
```
```
Graph of species range and distribution
```
```
Graph of species range and distribution within the plot (plot location)
```
Picture of tree cores (with a small blurb)

### *Sassafras albidum* (Nutt.) Nees ```Sassafras```
```
Life history (information will be added by Michael)
```
```
Leaf traits (written about or scanned and labeled)
```
```
Annual Recruitment and Mortality
# of trees (stems) in 2013 and 2018:
5-year mortality of trees (stems):
new tree recuitment:
max DBH in sample:
mean DBH in sample:
```
```
Graph of recruiment and mortality
{r echo=false}
hist()
```
```
Graph of species range and distribution
```
```
Graph of species range and distribution within the plot (plot location)
```
Picture of tree cores (with a small blurb)

## Magnoliaceae
### *Liriodendron tulipifera*	L. ```Tulip Poplar```
```
Life history (information will be added by Michael)
```
```
Leaf traits (written about or scanned and labeled)
```
```
Annual Recruitment and Mortality
# of trees (stems) in 2013 and 2018:
5-year mortality of trees (stems):
new tree recuitment:
max DBH in sample:
mean DBH in sample:
```
```
Graph of recruiment and mortality
{r echo=false}
hist()
```
```
Graph of species range and distribution
```
```
Graph of species range and distribution within the plot (plot location)
```
Picture of tree cores (with a small blurb)
## Malvaceae
### *Tilia americana* L. ```Basswood```
```
Life history (information will be added by Michael)
```
```
Leaf traits (written about or scanned and labeled)
```
```
Annual Recruitment and Mortality
# of trees (stems) in 2013 and 2018:
5-year mortality of trees (stems):
new tree recuitment:
max DBH in sample:
mean DBH in sample:
```
```
Graph of recruiment and mortality
{r echo=false}
hist()
```
```
Graph of species range and distribution
```
```
Graph of species range and distribution within the plot (plot location)
```
Picture of tree cores (with a small blurb)

## Nyssaceae
### *Nyssa sylvatica* Marsh. ```Black Gum```
```
Life history (information will be added by Michael)
```
```
Leaf traits (written about or scanned and labeled)
```
```
Annual Recruitment and Mortality
# of trees (stems) in 2013 and 2018:
5-year mortality of trees (stems):
new tree recuitment:
max DBH in sample:
mean DBH in sample:
```
```
Graph of recruiment and mortality
{r echo=false}
hist()
```
```
Graph of species range and distribution
```
```
Graph of species range and distribution within the plot (plot location)
```
Picture of tree cores (with a small blurb)

## Oleaceae
### *Chionanthus virginicus* L.	```Fringe Tree```
```
Life history (information will be added by Michael)
```
```
Leaf traits (written about or scanned and labeled)
```
```
Annual Recruitment and Mortality
# of trees (stems) in 2013 and 2018:
5-year mortality of trees (stems):
new tree recuitment:
max DBH in sample:
mean DBH in sample:
```
```
Graph of recruiment and mortality
{r echo=false}
hist()
```
```
Graph of species range and distribution
```
```
Graph of species range and distribution within the plot (plot location)
```
Picture of tree cores (with a small blurb)

### *Fraxinus americana* L. ```White Ash```
```
Life history (information will be added by Michael)
```
```
Leaf traits (written about or scanned and labeled)
```
```
Annual Recruitment and Mortality
# of trees (stems) in 2013 and 2018:
5-year mortality of trees (stems):
new tree recuitment:
max DBH in sample:
mean DBH in sample:
```
```
Graph of recruiment and mortality
{r echo=false}
hist()
```
```
Graph of species range and distribution
```
```
Graph of species range and distribution within the plot (plot location)
```
Picture of tree cores (with a small blurb)

### *Fraxinus nigra* Marsh.	```Black Ash```
```
Life history (information will be added by Michael)
```
```
Leaf traits (written about or scanned and labeled)
```
```
Annual Recruitment and Mortality
# of trees (stems) in 2013 and 2018:
5-year mortality of trees (stems):
new tree recuitment:
max DBH in sample:
mean DBH in sample:
```
```
Graph of recruiment and mortality
{r echo=false}
hist()
```
```
Graph of species range and distribution
```
```
Graph of species range and distribution within the plot (plot location)
```
Picture of tree cores (with a small blurb)

### *Fraxinus pennsylvanica* Marsh.	```Green Ash```
```
Life history (information will be added by Michael)
```
```
Leaf traits (written about or scanned and labeled)
```
```
Annual Recruitment and Mortality
# of trees (stems) in 2013 and 2018:
5-year mortality of trees (stems):
new tree recuitment:
max DBH in sample:
mean DBH in sample:
```
```
Graph of recruiment and mortality
{r echo=false}
hist()
```
```
Graph of species range and distribution
```
```
Graph of species range and distribution within the plot (plot location)
```
Picture of tree cores (with a small blurb)

## Paulowniaceae
### *Paulownia tomentosa*	(Thunb.) Sieb. & Zucc. ex Steud. ```Princess Tree```
```
Life history (information will be added by Michael)
```
```
Leaf traits (written about or scanned and labeled)
```
```
Annual Recruitment and Mortality
# of trees (stems) in 2013 and 2018:
5-year mortality of trees (stems):
new tree recuitment:
max DBH in sample:
mean DBH in sample:
```
```
Graph of recruiment and mortality
{r echo=false}
hist()
```
```
Graph of species range and distribution
```
```
Graph of species range and distribution within the plot (plot location)
```
Picture of tree cores (with a small blurb)

## Pinaceae
### *Pinus pungens*	Lamb. ```Table Mountain Pine```
```
Life history (information will be added by Michael)
```
```
Leaf traits (written about or scanned and labeled)
```
```
Annual Recruitment and Mortality
# of trees (stems) in 2013 and 2018:
5-year mortality of trees (stems):
new tree recuitment:
max DBH in sample:
mean DBH in sample:
```
```
Graph of recruiment and mortality
{r echo=false}
hist()
```
```
Graph of species range and distribution
```
```
Graph of species range and distribution within the plot (plot location)
```
Picture of tree cores (with a small blurb)

### *Pinus strobus* L. ```Eastern White Pine```
```
Life history (information will be added by Michael)
```
```
Leaf traits (written about or scanned and labeled)
```
```
Annual Recruitment and Mortality
# of trees (stems) in 2013 and 2018:
5-year mortality of trees (stems):
new tree recuitment:
max DBH in sample:
mean DBH in sample:
```
```
Graph of recruiment and mortality
{r echo=false}
hist()
```
```
Graph of species range and distribution
```
```
Graph of species range and distribution within the plot (plot location)
```
Picture of tree cores (with a small blurb)

### *Pinus virginiana* P. Mill.	```Virginia Pine```
```
Life history (information will be added by Michael)
```
```
Leaf traits (written about or scanned and labeled)
```
```
Annual Recruitment and Mortality
# of trees (stems) in 2013 and 2018:
5-year mortality of trees (stems):
new tree recuitment:
max DBH in sample:
mean DBH in sample:
```
```
Graph of recruiment and mortality
{r echo=false}
hist()
```
```
Graph of species range and distribution
```
```
Graph of species range and distribution within the plot (plot location)
```
Picture of tree cores (with a small blurb)

## Platanaceae
### *Platanus occidentalis* L. ```American Sycamore```
```
Life history (information will be added by Michael)
```
```
Leaf traits (written about or scanned and labeled)
```
```
Annual Recruitment and Mortality
# of trees (stems) in 2013 and 2018:
5-year mortality of trees (stems):
new tree recuitment:
max DBH in sample:
mean DBH in sample:
```
```
Graph of recruiment and mortality
{r echo=false}
hist()
```
```
Graph of species range and distribution
```
```
Graph of species range and distribution within the plot (plot location)
```
Picture of tree cores (with a small blurb)

## Rosaceae
### *Amelanchier arborea*	(Michx. f.) Fern. ```Downy Serviceberry```
```
Life history (information will be added by Michael)
```
```
Leaf traits (written about or scanned and labeled)
```
```
Annual Recruitment and Mortality
# of trees (stems) in 2013 and 2018:
5-year mortality of trees (stems):
new tree recuitment:
max DBH in sample:
mean DBH in sample:
```
```
Graph of recruiment and mortality
{r echo=false}
hist()
```
```
Graph of species range and distribution
```
```
Graph of species range and distribution within the plot (plot location)
```
Picture of tree cores (with a small blurb)

### *Crataegus pruniosa*	(Waxyfruit hawthorn)
```
Life history (information will be added by Michael)
```
```
Leaf traits (written about or scanned and labeled)
```
```
Annual Recruitment and Mortality
# of trees (stems) in 2013 and 2018:
5-year mortality of trees (stems):
new tree recuitment:
max DBH in sample:
mean DBH in sample:
```
```
Graph of recruiment and mortality
{r echo=false}
hist()
```
```
Graph of species range and distribution
```
```
Graph of species range and distribution within the plot (plot location)
```
Picture of tree cores (with a small blurb)

### *Prunus avium* (L.) L. ```Sweet cherry```
```
Life history (information will be added by Michael)
**Also known by common name Bird Cherry**
```
```
Leaf traits (written about or scanned and labeled)
```
```
Annual Recruitment and Mortality
# of trees (stems) in 2013 and 2018:
5-year mortality of trees (stems):
new tree recuitment:
max DBH in sample:
mean DBH in sample:
```
```
Graph of recruiment and mortality
{r echo=false}
hist()
```
```
Graph of species range and distribution
```
```
Graph of species range and distribution within the plot (plot location)
```
Picture of tree cores (with a small blurb)

### *Prunus persica* (L.) Batsch ```Peach```
```
Life history (information will be added by Michael)
```
```
Leaf traits (written about or scanned and labeled)
```
```
Annual Recruitment and Mortality
# of trees (stems) in 2013 and 2018:
5-year mortality of trees (stems):
new tree recuitment:
max DBH in sample:
mean DBH in sample:
```
```
Graph of recruiment and mortality
{r echo=false}
hist()
```
```
Graph of species range and distribution
```
```
Graph of species range and distribution within the plot (plot location)
```
Picture of tree cores (with a small blurb)

### *Prunus serotina* Ehrh. var serotina	```Black Cherry```
```
Life history (information will be added by Michael)
**Common name is also Wild Black Cherry.**
```
```
Leaf traits (written about or scanned and labeled)
```
```
Annual Recruitment and Mortality
# of trees (stems) in 2013 and 2018:
5-year mortality of trees (stems):
new tree recuitment:
max DBH in sample:
mean DBH in sample:
```
```
Graph of recruiment and mortality
{r echo=false}
hist()
```
```
Graph of species range and distribution
```
```
Graph of species range and distribution within the plot (plot location)
```
Picture of tree cores (with a small blurb)

### *Rosa multiflora* Thunb. ex Murr.	```Multiflora Rose```
```
Life history (information will be added by Michael)
```
```
Leaf traits (written about or scanned and labeled)
```
```
Annual Recruitment and Mortality
# of trees (stems) in 2013 and 2018:
5-year mortality of trees (stems):
new tree recuitment:
max DBH in sample:
mean DBH in sample:
```
```
Graph of recruiment and mortality
{r echo=false}
hist()
```
```
Graph of species range and distribution
```
```
Graph of species range and distribution within the plot (plot location)
```
Picture of tree cores (with a small blurb)

### *Rubus allegheniensis* Porter ```Allegheny Blackberry```
```
Life history (information will be added by Michael)
```
```
Leaf traits (written about or scanned and labeled)
```
```
Annual Recruitment and Mortality
# of trees (stems) in 2013 and 2018:
5-year mortality of trees (stems):
new tree recuitment:
max DBH in sample:
mean DBH in sample:
```
```
Graph of recruiment and mortality
{r echo=false}
hist()
```
```
Graph of species range and distribution
```
```
Graph of species range and distribution within the plot (plot location)
```
Picture of tree cores (with a small blurb)

### *Rubus pensilvanicus*	Poir. ```Pennsylvania Blackberry```
```
Life history (information will be added by Michael)
**This plant is also affectionally known as Prickly Blackberry.**
```
```
Leaf traits (written about or scanned and labeled)
```
```
Annual Recruitment and Mortality
# of trees (stems) in 2013 and 2018:
5-year mortality of trees (stems):
new tree recuitment:
max DBH in sample:
mean DBH in sample:
```
```
Graph of recruiment and mortality
{r echo=false}
hist()
```
```
Graph of species range and distribution
```
```
Graph of species range and distribution within the plot (plot location)
```
Picture of tree cores (with a small blurb)

*Rubus phoenicolasius* Maxim.	```Wineberry```
```
Life history (information will be added by Michael)
```
```
Leaf traits (written about or scanned and labeled)
```
```
Annual Recruitment and Mortality
# of trees (stems) in 2013 and 2018:
5-year mortality of trees (stems):
new tree recuitment:
max DBH in sample:
mean DBH in sample:
```
```
Graph of recruiment and mortality
{r echo=false}
hist()
```
```
Graph of species range and distribution
```
```
Graph of species range and distribution within the plot (plot location)
```
Picture of tree cores (with a small blurb)

## Sapindaceae
### *Acer negundo* L. var negundo ```Boxelder```
```
Life history (information will be added by Michael)
**Second common name is Eastern Boxelder.**
```
```
Leaf traits (written about or scanned and labeled)
```
```
Annual Recruitment and Mortality
# of trees (stems) in 2013 and 2018:
5-year mortality of trees (stems):
new tree recuitment:
max DBH in sample:
mean DBH in sample:
```
```
Graph of recruiment and mortality
{r echo=false}
hist()
```
```
Graph of species range and distribution
```
```
Graph of species range and distribution within the plot (plot location)
```
Picture of tree cores (with a small blurb)

### *Acer platanoides* L.	```Norway Maple```
```
Life history (information will be added by Michael)
```
```
Leaf traits (written about or scanned and labeled)
```
```
Annual Recruitment and Mortality
# of trees (stems) in 2013 and 2018:
5-year mortality of trees (stems):
new tree recuitment:
max DBH in sample:
mean DBH in sample:
```
```
Graph of recruiment and mortality
{r echo=false}
hist()
```
```
Graph of species range and distribution
```
```
Graph of species range and distribution within the plot (plot location)
```
Picture of tree cores (with a small blurb)

### *Acer rubrum*	L. ```Red Maple```
```
Life history (information will be added by Michael)
```
```
Leaf traits (written about or scanned and labeled)
```
```
Annual Recruitment and Mortality
# of trees (stems) in 2013 and 2018:
5-year mortality of trees (stems):
new tree recuitment:
max DBH in sample:
mean DBH in sample:
```
```
Graph of recruiment and mortality
{r echo=false}
hist()
```
```
Graph of species range and distribution
```
```
Graph of species range and distribution within the plot (plot location)
```
Picture of tree cores (with a small blurb)

## Simaroubaceae
### *Ailanthus altissima* (P. Miller) Swingle ```Tree of Heaven```
```
Life history (information will be added by Michael)
```
```
Leaf traits (written about or scanned and labeled)
```
```
Annual Recruitment and Mortality
# of trees (stems) in 2013 and 2018:
5-year mortality of trees (stems):
new tree recuitment:
max DBH in sample:
mean DBH in sample:
```
```
Graph of recruiment and mortality
{r echo=false}
hist()
```
```
Graph of species range and distribution
```
```
Graph of species range and distribution within the plot (plot location)
```
Picture of tree cores (with a small blurb)

## Ulmaceae
### *Ulmus americana*	L. ```American Elm```
```
Life history (information will be added by Michael)
```
```
Leaf traits (written about or scanned and labeled)
```
```
Annual Recruitment and Mortality
# of trees (stems) in 2013 and 2018:
5-year mortality of trees (stems):
new tree recuitment:
max DBH in sample:
mean DBH in sample:
```
```
Graph of recruiment and mortality
{r echo=false}
hist()
```
```
Graph of species range and distribution
```
```
Graph of species range and distribution within the plot (plot location)
```
Picture of tree cores (with a small blurb)

### *Ulmus rubra*	Muhl. ```Slippery Elm```
```
Life history (information will be added by Michael)
**Species is also commonly known as Red Elm.**
```
```
Leaf traits (written about or scanned and labeled)
```
```
Annual Recruitment and Mortality
# of trees (stems) in 2013 and 2018:
5-year mortality of trees (stems):
new tree recuitment:
max DBH in sample:
mean DBH in sample:
```
```
Graph of recruiment and mortality
{r echo=false}
hist()
```
```
Graph of species range and distribution
```
```
Graph of species range and distribution within the plot (plot location)
```
Picture of tree cores (with a small blurb)
