---
title: "SCBI: Plot Book"
author: "Kristina Anderson-Teixeira, Erika Gonzalez-Akre, Stuart Davies, William McShea, Alyssa Terrell, Michael Scott, Caroline Kittle, Ian McGregor"
date: "2018"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```
# Chapter 1: Introduction
Forests make up 45% of terrestrial carbon (Bonan 2008 and Stovall et al. 2018). The amount of carbon held in by trees can have a negative impact due to the emissions that are released into the air caused by deforestation. The rise in carbon emissions is attributed to the rise in tree mortality.

Mortality is one of the most important causes of forest dynamics (Gonzalez-Akre et al. 2016), as it can influnce the number and distribution of woody species that are found in an area. It can also be detrimental because tree mortality can be used as an indication of climate change (Gonzalez-Akre 2016).


In 1974, the Smithsonian purchased a piece of land, known as the Remount Depot. Shortly after the purchase, the land became the Conservation Research Center.The Front Royal site of the National Zoological Park is ~1,296 hectares (3,500 acres) and combined with research and academic facilities, forestry, pastures, and animal enclosures (ASK ERIKA OR KRISTA HOW TO CITE THE CULTURAL RESOUCE ASSESSMENT - Ayers et al. 2007).


# Chapter 2: Physical Environment
The dynamic plot is located at the Smithsonian Conservation Biology Institute (SCBI) in Virginia, U.S.A (38°53'36.6"N, 78°08'43.4"W) with the elevation ranging from 273m to 338m (Gozalez-Akre et al. 2016). The research site is a temperate deciduous forest within a 25.6-hectare plot set up 640m by 400m (Bourg et al. 2013).

This part of the document will be describing the research site. This part should include climate (include graph used in mortality paper), topography (graphs created by Ian), and soil information

**I think it would be beneficial to include figure 2 from Stovall et al. 2018**
"The top 10 domintant species contributing over 80% of biomass within the ForestGEO forest as estimated using the Chonjnacky et al. (2014) equations."


# Chapter 3: Methods
This survey was conducted in the Center for Tropical Forest Science-Forest Global Earth Observatory's (CTFS-ForestGEO) dynamic forest plot. The plot, itself, is located at the Smithsonian Conservation Biology Institute in Front Royal, Virginia, USA. SCBI is 3.1 miles (5 kilometers) from the Shenandoah National Park and roughly 80 miles (~130 kilometers) from the Smithsonian National Zoological Park.

The research was conducted by a team of interns under the labs of William McShea, Ph.D and Kristina Anderson-Teixeira, Ph.D. On average, 3.3 people/day participated in the census with 3.7 field days/week. A single person logged an average of 29 hours/week, resulting in 97 hours/week being done. Roughly 3,200 total amount of work hours - including data collection, review, entry, and analysis - was completed.

The survey team utilized methods set by the Center for Tropical Forest Science - Forest Global Earth Observatory, also known as CTFS-ForestGEO (Condit 1998 and Gonzalez-Akre et al. 2016). Measurements of old, new multi-, and new plant stems are either measured or recruited at "\???1"cm DBH (Bourg et al. 2013). "Old stems" are considered to be stems that existed in the previous census. These measurements also include old multistemed species. "New multi stems" are new stems that have grown on the same woody species as the old stem. "New plant stems" are the new growth of species that have not been tagged in the plot yet. "Tagging" is when a woody species is marked with a specific identification number. These numbers are compiled within a spread sheet and logged into the global CTFS database.


Gonzalez-Akre et al. 2016:
- Dead stems are considered to be dead due to the following criteria: (1) stems that are broken below DBH; (2) loosened or detached bark; (3) lack of development in regards to flower or leaf buds and; (4) signs of pests or pathogens such as fungus and insects.

Ramage et al. 2017:
- 4 hectares of the plot is fenced in to keep out *Odocoileus virginianus (white-tailed deer) - area will further be refered to as the deer exclosure

Give credit to Bourg et al. 2013:
- measured and recruited all stems "\???1"cm DBH
- recruitment includes tagging and identification of stems



# Chapter 4: Woody Plants
For life history, mention common canopy positions
  - information from Ramage et al. 2017
    - dominant canopy are *Liriondendron tulipifera* (tulip poplar), *Carya* spp., *Quercus* spp., *Fraxinus americana* (white ash), *Nyssa sylvatica* (black gum)

##Adoxaceae
### *Sambucus canadensis* (L.) R. Bolli ```American Black Elderberry```
```
Life history (information will be added by Michael)
```
```
Leaf traits (written about or scanned and labeled)
```
```
Annual Recruitment and Mortality
# of trees (stems) in 2013 and 2018:
5-year mortality of trees (stems):
new tree recuitment:
max DBH in sample:
mean DBH in sample:
```
```
Graph of recruiment and mortality
{r echo=false}
hist()
```
```
Graph of species range and distribution
```
```
Graph of species range and distribution within the plot (plot location)
```
Picture of tree cores (with a small blurb)

### *Viburnum acerifolium* L. ```Mapleleaf Viburnum```
```
Life history (information will be added by Michael)
```
```
Leaf traits (written about or scanned and labeled)
```
```
Annual Recruitment and Mortality
# of trees (stems) in 2013 and 2018:
5-year mortality of trees (stems):
new tree recuitment:
max DBH in sample:
mean DBH in sample:
```
```
Graph of recruiment and mortality
{r echo=false}
hist()
```
```
Graph of species range and distribution
```
```
Graph of species range and distribution within the plot (plot location)
```
Picture of tree cores (with a small blurb)

###	*Viburnum prunifolium* L. ```Black Haw```
```
Life history (information will be added by Michael)
```
```
Leaf traits (written about or scanned and labeled)
```
```
Annual Recruitment and Mortality
# of trees (stems) in 2013 and 2018:
5-year mortality of trees (stems):
new tree recuitment:
max DBH in sample:
mean DBH in sample:
```
```
Graph of recruiment and mortality
{r echo=false}
hist()
```
```
Graph of species range and distribution
```
```
Graph of species range and distribution within the plot (plot location)
```
Picture of tree cores (with a small blurb)

###	*Viburnum recognitum* Fernald ```Southern Arrow-wood```
```
Life history (information will be added by Michael)
***also known as *Virburnum dentatum* L.***
```
```
Leaf traits (written about or scanned and labeled)
```
```
Annual Recruitment and Mortality
# of trees (stems) in 2013 and 2018:
5-year mortality of trees (stems):
new tree recuitment:
max DBH in sample:
mean DBH in sample:
```
```
Graph of recruiment and mortality
{r echo=false}
hist()
```
```
Graph of species range and distribution
```
```
Graph of species range and distribution within the plot (plot location)
```
Picture of tree cores (with a small blurb)

## Annonaceae
### *Asimina triloba*	(L.) Dunal ```Pawpaw```
```
Life history (information will be added by Michael)
```
```
Leaf traits (written about or scanned and labeled)
```
```
Annual Recruitment and Mortality
# of trees (stems) in 2013 and 2018:
5-year mortality of trees (stems):
new tree recuitment:
max DBH in sample:
mean DBH in sample:
```
```
Graph of recruiment and mortality
{r echo=false}
hist()
```
```
Graph of species range and distribution
```
```
Graph of species range and distribution within the plot (plot location)
```
Picture of tree cores (with a small blurb)

##Aquifoliaceae
### *Ilex verticillata* (L.) A. Gray ```Common Winterberry```
```
Life history (information will be added by Michael)
```
```
Leaf traits (written about or scanned and labeled)
```
```
Annual Recruitment and Mortality
# of trees (stems) in 2013 and 2018:
5-year mortality of trees (stems):
new tree recuitment:
max DBH in sample:
mean DBH in sample:
```
```
Graph of recruiment and mortality
{r echo=false}
hist()
```
```
Graph of species range and distribution
```
```
Graph of species range and distribution within the plot (plot location)
```
Picture of tree cores (with a small blurb)

##Berberidaceae
### *Berberis thunbergii* DC. ```Japanese Barberry```
```
Life history (information will be added by Michael)
```
```
Leaf traits (written about or scanned and labeled)
```
```
Annual Recruitment and Mortality
# of trees (stems) in 2013 and 2018:
5-year mortality of trees (stems):
new tree recuitment:
max DBH in sample:
mean DBH in sample:
```
```
Graph of recruiment and mortality
{r echo=false}
hist()
```
```
Graph of species range and distribution
```
```
Graph of species range and distribution within the plot (plot location)
```
Picture of tree cores (with a small blurb)

## Betulaceae
### *Carpinus caroliniana* Walt. ```American Hornbeam```
```
Life history (information will be added by Michael)
```
```
Leaf traits (written about or scanned and labeled)
```
```
Annual Recruitment and Mortality
# of trees (stems) in 2013 and 2018:
5-year mortality of trees (stems):
new tree recuitment:
max DBH in sample:
mean DBH in sample:
```
```
Graph of recruiment and mortality
{r echo=false}
hist()
```
```
Graph of species range and distribution
```
```
Graph of species range and distribution within the plot (plot location)
```
Picture of tree cores (with a small blurb)

###	*Corylus americana*	Walt. ```American Hazelnut```
```
Life history (information will be added by Michael)
```
```
Leaf traits (written about or scanned and labeled)
```
```
Annual Recruitment and Mortality
# of trees (stems) in 2013 and 2018:
5-year mortality of trees (stems):
new tree recuitment:
max DBH in sample:
mean DBH in sample:
```
```
Graph of recruiment and mortality
{r echo=false}
hist()
```
```
Graph of species range and distribution
```
```
Graph of species range and distribution within the plot (plot location)
```
Picture of tree cores (with a small blurb)

## Cannabaceae
### *Celtis occidentalis*	L. ```Hackberry```
```
Life history (information will be added by Michael)
```
```
Leaf traits (written about or scanned and labeled)
```
```
Annual Recruitment and Mortality
# of trees (stems) in 2013 and 2018:
5-year mortality of trees (stems):
new tree recuitment:
max DBH in sample:
mean DBH in sample:
```
```
Graph of recruiment and mortality
{r echo=false}
hist()
```
```
Graph of species range and distribution
```
```
Graph of species range and distribution within the plot (plot location)
```
Picture of tree cores (with a small blurb)

## Caprifoliaceae
### *Lonicera maackii* (Rupr.) Maxim ```Bush Honeysuckle```
```
Life history (information will be added by Michael)
```
```
Leaf traits (written about or scanned and labeled)
```
```
Annual Recruitment and Mortality
# of trees (stems) in 2013 and 2018:
5-year mortality of trees (stems):
new tree recuitment:
max DBH in sample:
mean DBH in sample:
```
```
Graph of recruiment and mortality
{r echo=false}
hist()
```
```
Graph of species range and distribution
```
```
Graph of species range and distribution within the plot (plot location)
```
Picture of tree cores (with a small blurb)

## Celastracea
### *Euonymus alatus* (Thunb.) Sieb. ```Burning Bush```
```
Life history (information will be added by Michael)
**Species is also known as Winged Euonymus.**
```
```
Leaf traits (written about or scanned and labeled)
```
```
Annual Recruitment and Mortality
# of trees (stems) in 2013 and 2018:
5-year mortality of trees (stems):
new tree recuitment:
max DBH in sample:
mean DBH in sample:
```
```
Graph of recruiment and mortality
{r echo=false}
hist()
```
```
Graph of species range and distribution
```
```
Graph of species range and distribution within the plot (plot location)
```
Picture of tree cores (with a small blurb)

## Cornaceae
### *Cornus alternifolia*	L. f. ```Alternate Leaf Dogwood```
```
Life history (information will be added by Michael)
```
```
Leaf traits (written about or scanned and labeled)
```
```
Annual Recruitment and Mortality
# of trees (stems) in 2013 and 2018:
5-year mortality of trees (stems):
new tree recuitment:
max DBH in sample:
mean DBH in sample:
```
```
Graph of recruiment and mortality
{r echo=false}
hist()
```
```
Graph of species range and distribution
```
```
Graph of species range and distribution within the plot (plot location)
```
Picture of tree cores (with a small blurb)

### *Cornus florida* L. ```Flowering Dogwood```
```
Life history (information will be added by Michael)
```
```
Leaf traits (written about or scanned and labeled)
```
```
Annual Recruitment and Mortality
# of trees (stems) in 2013 and 2018:
5-year mortality of trees (stems):
new tree recuitment:
max DBH in sample:
mean DBH in sample:
```
```
Graph of recruiment and mortality
{r echo=false}
hist()
```
```
Graph of species range and distribution
```
```
Graph of species range and distribution within the plot (plot location)
```
Picture of tree cores (with a small blurb)

## Ebenaceae
### *Diospyros virginiana* L. ```Persimmon```
```
Life history (information will be added by Michael)
```
```
Leaf traits (written about or scanned and labeled)
```
```
Annual Recruitment and Mortality
# of trees (stems) in 2013 and 2018:
5-year mortality of trees (stems):
new tree recuitment:
max DBH in sample:
mean DBH in sample:
```
```
Graph of recruiment and mortality
{r echo=false}
hist()
```
```
Graph of species range and distribution
```
```
Graph of species range and distribution within the plot (plot location)
```
Picture of tree cores (with a small blurb)

## Elaeagnaceae
### *Elaeagnus umbellata*	Thunb. ```Autumn Olive```
```
Life history (information will be added by Michael)
```
```
Leaf traits (written about or scanned and labeled)
```
```
Annual Recruitment and Mortality
# of trees (stems) in 2013 and 2018:
5-year mortality of trees (stems):
new tree recuitment:
max DBH in sample:
mean DBH in sample:
```
```
Graph of recruiment and mortality
{r echo=false}
hist()
```
```
Graph of species range and distribution
```
```
Graph of species range and distribution within the plot (plot location)
```
Picture of tree cores (with a small blurb)

## Fabaceae
### *Cercis canadensis* L. ```Eastern Redbud```
```
Life history (information will be added by Michael)
```
```
Leaf traits (written about or scanned and labeled)
```
```
Annual Recruitment and Mortality
# of trees (stems) in 2013 and 2018:
5-year mortality of trees (stems):
new tree recuitment:
max DBH in sample:
mean DBH in sample:
```
```
Graph of recruiment and mortality
{r echo=false}
hist()
```
```
Graph of species range and distribution
```
```
Graph of species range and distribution within the plot (plot location)
```
Picture of tree cores (with a small blurb)

### *Robinia pseudoacacia* L. ```Black Locust```
```
Life history (information will be added by Michael)
```
```
Leaf traits (written about or scanned and labeled)
```
```
Annual Recruitment and Mortality
# of trees (stems) in 2013 and 2018:
5-year mortality of trees (stems):
new tree recuitment:
max DBH in sample:
mean DBH in sample:
```
```
Graph of recruiment and mortality
{r echo=false}
hist()
```
```
Graph of species range and distribution
```
```
Graph of species range and distribution within the plot (plot location)
```
Picture of tree cores (with a small blurb)

## Fagaceae
### *Castanea dentata* (Marsh.) Borkh. ```American Chestnut```
```
Life history (information will be added by Michael)
```
```
Leaf traits (written about or scanned and labeled)
```
```
Annual Recruitment and Mortality
# of trees (stems) in 2013 and 2018:
5-year mortality of trees (stems):
new tree recuitment:
max DBH in sample:
mean DBH in sample:
```
```
Graph of recruiment and mortality
{r echo=false}
hist()
```
```
Graph of species range and distribution
```
```
Graph of species range and distribution within the plot (plot location)
```
Picture of tree cores (with a small blurb)

### *Fagus grandifolia*	Ehrh. ```American Beech```
```
Life history (information will be added by Michael)
```
```
Leaf traits (written about or scanned and labeled)
```
```
Annual Recruitment and Mortality
# of trees (stems) in 2013 and 2018:
5-year mortality of trees (stems):
new tree recuitment:
max DBH in sample:
mean DBH in sample:
```
```
Graph of recruiment and mortality
{r echo=false}
hist()
```
```
Graph of species range and distribution
```
```
Graph of species range and distribution within the plot (plot location)
```
Picture of tree cores (with a small blurb)

### *Quercus alba* L. ```White Oak```
```
Life history (information will be added by Michael)
```
```
Leaf traits (written about or scanned and labeled)
```
```
Annual Recruitment and Mortality
# of trees (stems) in 2013 and 2018:
5-year mortality of trees (stems):
new tree recuitment:
max DBH in sample:
mean DBH in sample:
```
```
Graph of recruiment and mortality
{r echo=false}
hist()
```
```
Graph of species range and distribution
```
```
Graph of species range and distribution within the plot (plot location)
```
Picture of tree cores (with a small blurb)

### *Quercus coccinea* Muenchh. ```Scarlet Oak```
```
Life history (information will be added by Michael)
```
```
Leaf traits (written about or scanned and labeled)
```
```
Annual Recruitment and Mortality
# of trees (stems) in 2013 and 2018:
5-year mortality of trees (stems):
new tree recuitment:
max DBH in sample:
mean DBH in sample:
```
```
Graph of recruiment and mortality
{r echo=false}
hist()
```
```
Graph of species range and distribution
```
```
Graph of species range and distribution within the plot (plot location)
```
Picture of tree cores (with a small blurb)

### *Quercus falcata* Michx. ```Southern Red Oak```
```
Life history (information will be added by Michael)
```
```
Leaf traits (written about or scanned and labeled)
```
```
Annual Recruitment and Mortality
# of trees (stems) in 2013 and 2018:
5-year mortality of trees (stems):
new tree recuitment:
max DBH in sample:
mean DBH in sample:
```
```
Graph of recruiment and mortality
{r echo=false}
hist()
```
```
Graph of species range and distribution
```
```
Graph of species range and distribution within the plot (plot location)
```
Picture of tree cores (with a small blurb)

### *Quercus michauxii* Nutt. ```Swamp Chestnut Oak```
```
Life history (information will be added by Michael)
```
```
Leaf traits (written about or scanned and labeled)
```
```
Annual Recruitment and Mortality
# of trees (stems) in 2013 and 2018:
5-year mortality of trees (stems):
new tree recuitment:
max DBH in sample:
mean DBH in sample:
```
```
Graph of recruiment and mortality
{r echo=false}
hist()
```
```
Graph of species range and distribution
```
```
Graph of species range and distribution within the plot (plot location)
```
Picture of tree cores (with a small blurb)

### *Quercus muehlenbergii* Engelm. ```Chinkapin Oak```
```
Life history (information will be added by Michael)
```
```
Leaf traits (written about or scanned and labeled)
```
```
Annual Recruitment and Mortality
# of trees (stems) in 2013 and 2018:
5-year mortality of trees (stems):
new tree recuitment:
max DBH in sample:
mean DBH in sample:
```
```
Graph of recruiment and mortality
{r echo=false}
hist()
```
```
Graph of species range and distribution
```
```
Graph of species range and distribution within the plot (plot location)
```
Picture of tree cores (with a small blurb)

### *Quercus montana* Willd. ```Chestnut Oak```
**Formally known as *Quercus prinus* L.**
```
Life history (information will be added by Michael)
```
```
Leaf traits (written about or scanned and labeled)
```
```
Annual Recruitment and Mortality
# of trees (stems) in 2013 and 2018:
5-year mortality of trees (stems):
new tree recuitment:
max DBH in sample:
mean DBH in sample:
```
```
Graph of recruiment and mortality
{r echo=false}
hist()
```
```
Graph of species range and distribution
```
```
Graph of species range and distribution within the plot (plot location)
```
Picture of tree cores (with a small blurb)

### *Quercus rubra*	L. ```Northern Red Oak```
```
Life history (information will be added by Michael)
```
```
Leaf traits (written about or scanned and labeled)
```
```
Annual Recruitment and Mortality
# of trees (stems) in 2013 and 2018:
5-year mortality of trees (stems):
new tree recuitment:
max DBH in sample:
mean DBH in sample:
```
```
Graph of recruiment and mortality
{r echo=false}
hist()
```
```
Graph of species range and distribution
```
```
Graph of species range and distribution within the plot (plot location)
```
Picture of tree cores (with a small blurb)

### *Quercus velutina* Lam.	```Black Oak```
```
Life history (information will be added by Michael)
```
```
Leaf traits (written about or scanned and labeled)
```
```
Annual Recruitment and Mortality
# of trees (stems) in 2013 and 2018:
5-year mortality of trees (stems):
new tree recuitment:
max DBH in sample:
mean DBH in sample:
```
```
Graph of recruiment and mortality
{r echo=false}
hist()
```
```
Graph of species range and distribution
```
```
Graph of species range and distribution within the plot (plot location)
```
Picture of tree cores (with a small blurb)

## Hamamelidaceae
### *Hamamelis virginiana* L. var. virginiana	```Witch Hazel```
```
Life history (information will be added by Michael)
```
```
Leaf traits (written about or scanned and labeled)
```
```
Annual Recruitment and Mortality
# of trees (stems) in 2013 and 2018:
5-year mortality of trees (stems):
new tree recuitment:
max DBH in sample:
mean DBH in sample:
```
```
Graph of recruiment and mortality
{r echo=false}
hist()
```
```
Graph of species range and distribution
```
```
Graph of species range and distribution within the plot (plot location)
```
Picture of tree cores (with a small blurb)

## Juglandaceae
### *Carya cordiformis* (Wangenh.) K. Koch	```Bitternut Hickory```
```
Life history (information will be added by Michael)
```
```
Leaf traits (written about or scanned and labeled)
```
```
Annual Recruitment and Mortality
# of trees (stems) in 2013 and 2018:
5-year mortality of trees (stems):
new tree recuitment:
max DBH in sample:
mean DBH in sample:
```
```
Graph of recruiment and mortality
{r echo=false}
hist()
```
```
Graph of species range and distribution
```
```
Graph of species range and distribution within the plot (plot location)
```
Picture of tree cores (with a small blurb)

### *Carya glabra* (P. Mill.) ```Pignut Hickory```
```
Life history (information will be added by Michael)
```
```
Leaf traits (written about or scanned and labeled)
```
```
Annual Recruitment and Mortality
# of trees (stems) in 2013 and 2018:
5-year mortality of trees (stems):
new tree recuitment:
max DBH in sample:
mean DBH in sample:
```
```
Graph of recruiment and mortality
{r echo=false}
hist()
```
```
Graph of species range and distribution
```
```
Graph of species range and distribution within the plot (plot location)
```
Picture of tree cores (with a small blurb)

### *Carya ovalis* (Wangenh.) Sarg.	```Red Hickory```
```
Life history (information will be added by Michael)
```
```
Leaf traits (written about or scanned and labeled)
```
```
Annual Recruitment and Mortality
# of trees (stems) in 2013 and 2018:
5-year mortality of trees (stems):
new tree recuitment:
max DBH in sample:
mean DBH in sample:
```
```
Graph of recruiment and mortality
{r echo=false}
hist()
```
```
Graph of species range and distribution
```
```
Graph of species range and distribution within the plot (plot location)
```
Picture of tree cores (with a small blurb)

### *Carya tomentosa* (Lam. ex Pior.) Nutt.	```Mockernut Hickory```
```
Life history (information will be added by Michael)
```
```
Leaf traits (written about or scanned and labeled)
```
```
Annual Recruitment and Mortality
# of trees (stems) in 2013 and 2018:
5-year mortality of trees (stems):
new tree recuitment:
max DBH in sample:
mean DBH in sample:
```
```
Graph of recruiment and mortality
{r echo=false}
hist()
```
```
Graph of species range and distribution
```
```
Graph of species range and distribution within the plot (plot location)
```
Picture of tree cores (with a small blurb)

### *Juglans cinerea* L. ```Butternut```
```
Life history (information will be added by Michael)
```
```
Leaf traits (written about or scanned and labeled)
```
```
Annual Recruitment and Mortality
# of trees (stems) in 2013 and 2018:
5-year mortality of trees (stems):
new tree recuitment:
max DBH in sample:
mean DBH in sample:
```
```
Graph of recruiment and mortality
{r echo=false}
hist()
```
```
Graph of species range and distribution
```
```
Graph of species range and distribution within the plot (plot location)
```
Picture of tree cores (with a small blurb)

### *Juglans nigra*	L. ```Black Walnut```
```
Life history (information will be added by Michael)
```
```
Leaf traits (written about or scanned and labeled)
```
```
Annual Recruitment and Mortality
# of trees (stems) in 2013 and 2018:
5-year mortality of trees (stems):
new tree recuitment:
max DBH in sample:
mean DBH in sample:
```
```
Graph of recruiment and mortality
{r echo=false}
hist()
```
```
Graph of species range and distribution
```
```
Graph of species range and distribution within the plot (plot location)
```
Picture of tree cores (with a small blurb)

## Lauraceae
### *Lindera benzoin* (L.) Blume	```Spicebush```
```
Life history (information will be added by Michael)
```
```
Leaf traits (written about or scanned and labeled)
```
```
Annual Recruitment and Mortality
# of trees (stems) in 2013 and 2018:
5-year mortality of trees (stems):
new tree recuitment:
max DBH in sample:
mean DBH in sample:
```
```
Graph of recruiment and mortality
{r echo=false}
hist()
```
```
Graph of species range and distribution
```
```
Graph of species range and distribution within the plot (plot location)
```
Picture of tree cores (with a small blurb)

### *Sassafras albidum* (Nutt.) Nees ```Sassafras```
```
Life history (information will be added by Michael)
```
```
Leaf traits (written about or scanned and labeled)
```
```
Annual Recruitment and Mortality
# of trees (stems) in 2013 and 2018:
5-year mortality of trees (stems):
new tree recuitment:
max DBH in sample:
mean DBH in sample:
```
```
Graph of recruiment and mortality
{r echo=false}
hist()
```
```
Graph of species range and distribution
```
```
Graph of species range and distribution within the plot (plot location)
```
Picture of tree cores (with a small blurb)

## Magnoliaceae
### *Liriodendron tulipifera*	L. ```Tulip Poplar```
```
Life history (information will be added by Michael)
```
```
Leaf traits (written about or scanned and labeled)
```
```
Annual Recruitment and Mortality
# of trees (stems) in 2013 and 2018:
5-year mortality of trees (stems):
new tree recuitment:
max DBH in sample:
mean DBH in sample:
```
```
Graph of recruiment and mortality
{r echo=false}
hist()
```
```
Graph of species range and distribution
```
```
Graph of species range and distribution within the plot (plot location)
```
Picture of tree cores (with a small blurb)
## Malvaceae
### *Tilia americana* L. ```Basswood```
```
Life history (information will be added by Michael)
```
```
Leaf traits (written about or scanned and labeled)
```
```
Annual Recruitment and Mortality
# of trees (stems) in 2013 and 2018:
5-year mortality of trees (stems):
new tree recuitment:
max DBH in sample:
mean DBH in sample:
```
```
Graph of recruiment and mortality
{r echo=false}
hist()
```
```
Graph of species range and distribution
```
```
Graph of species range and distribution within the plot (plot location)
```
Picture of tree cores (with a small blurb)

## Nyssaceae
### *Nyssa sylvatica* Marsh. ```Black Gum```
```
Life history (information will be added by Michael)
```
```
Leaf traits (written about or scanned and labeled)
```
```
Annual Recruitment and Mortality
# of trees (stems) in 2013 and 2018:
5-year mortality of trees (stems):
new tree recuitment:
max DBH in sample:
mean DBH in sample:
```
```
Graph of recruiment and mortality
{r echo=false}
hist()
```
```
Graph of species range and distribution
```
```
Graph of species range and distribution within the plot (plot location)
```
Picture of tree cores (with a small blurb)

## Oleaceae
### *Chionanthus virginicus* L.	```Fringe Tree```
```
Life history (information will be added by Michael)
```
```
Leaf traits (written about or scanned and labeled)
```
```
Annual Recruitment and Mortality
# of trees (stems) in 2013 and 2018:
5-year mortality of trees (stems):
new tree recuitment:
max DBH in sample:
mean DBH in sample:
```
```
Graph of recruiment and mortality
{r echo=false}
hist()
```
```
Graph of species range and distribution
```
```
Graph of species range and distribution within the plot (plot location)
```
Picture of tree cores (with a small blurb)

### *Fraxinus americana* L. ```White Ash```
```
Life history (information will be added by Michael)
```
```
Leaf traits (written about or scanned and labeled)
```
```
Annual Recruitment and Mortality
# of trees (stems) in 2013 and 2018:
5-year mortality of trees (stems):
new tree recuitment:
max DBH in sample:
mean DBH in sample:
```
```
Graph of recruiment and mortality
{r echo=false}
hist()
```
```
Graph of species range and distribution
```
```
Graph of species range and distribution within the plot (plot location)
```
Picture of tree cores (with a small blurb)

### *Fraxinus nigra* Marsh.	```Black Ash```
```
Life history (information will be added by Michael)
```
```
Leaf traits (written about or scanned and labeled)
```
```
Annual Recruitment and Mortality
# of trees (stems) in 2013 and 2018:
5-year mortality of trees (stems):
new tree recuitment:
max DBH in sample:
mean DBH in sample:
```
```
Graph of recruiment and mortality
{r echo=false}
hist()
```
```
Graph of species range and distribution
```
```
Graph of species range and distribution within the plot (plot location)
```
Picture of tree cores (with a small blurb)

### *Fraxinus pennsylvanica* Marsh.	```Green Ash```
```
Life history (information will be added by Michael)
```
```
Leaf traits (written about or scanned and labeled)
```
```
Annual Recruitment and Mortality
# of trees (stems) in 2013 and 2018:
5-year mortality of trees (stems):
new tree recuitment:
max DBH in sample:
mean DBH in sample:
```
```
Graph of recruiment and mortality
{r echo=false}
hist()
```
```
Graph of species range and distribution
```
```
Graph of species range and distribution within the plot (plot location)
```
Picture of tree cores (with a small blurb)

## Paulowniaceae
### *Paulownia tomentosa*	(Thunb.) Sieb. & Zucc. ex Steud. ```Princess Tree```
```
Life history (information will be added by Michael)
```
```
Leaf traits (written about or scanned and labeled)
```
```
Annual Recruitment and Mortality
# of trees (stems) in 2013 and 2018:
5-year mortality of trees (stems):
new tree recuitment:
max DBH in sample:
mean DBH in sample:
```
```
Graph of recruiment and mortality
{r echo=false}
hist()
```
```
Graph of species range and distribution
```
```
Graph of species range and distribution within the plot (plot location)
```
Picture of tree cores (with a small blurb)

## Pinaceae
### *Pinus pungens*	Lamb. ```Table Mountain Pine```
```
Life history (information will be added by Michael)
```
```
Leaf traits (written about or scanned and labeled)
```
```
Annual Recruitment and Mortality
# of trees (stems) in 2013 and 2018:
5-year mortality of trees (stems):
new tree recuitment:
max DBH in sample:
mean DBH in sample:
```
```
Graph of recruiment and mortality
{r echo=false}
hist()
```
```
Graph of species range and distribution
```
```
Graph of species range and distribution within the plot (plot location)
```
Picture of tree cores (with a small blurb)

### *Pinus strobus* L. ```Eastern White Pine```
```
Life history (information will be added by Michael)
```
```
Leaf traits (written about or scanned and labeled)
```
```
Annual Recruitment and Mortality
# of trees (stems) in 2013 and 2018:
5-year mortality of trees (stems):
new tree recuitment:
max DBH in sample:
mean DBH in sample:
```
```
Graph of recruiment and mortality
{r echo=false}
hist()
```
```
Graph of species range and distribution
```
```
Graph of species range and distribution within the plot (plot location)
```
Picture of tree cores (with a small blurb)

### *Pinus virginiana* P. Mill.	```Virginia Pine```
```
Life history (information will be added by Michael)
```
```
Leaf traits (written about or scanned and labeled)
```
```
Annual Recruitment and Mortality
# of trees (stems) in 2013 and 2018:
5-year mortality of trees (stems):
new tree recuitment:
max DBH in sample:
mean DBH in sample:
```
```
Graph of recruiment and mortality
{r echo=false}
hist()
```
```
Graph of species range and distribution
```
```
Graph of species range and distribution within the plot (plot location)
```
Picture of tree cores (with a small blurb)

## Platanaceae
### *Platanus occidentalis* L. ```American Sycamore```
```
Life history (information will be added by Michael)
```
```
Leaf traits (written about or scanned and labeled)
```
```
Annual Recruitment and Mortality
# of trees (stems) in 2013 and 2018:
5-year mortality of trees (stems):
new tree recuitment:
max DBH in sample:
mean DBH in sample:
```
```
Graph of recruiment and mortality
{r echo=false}
hist()
```
```
Graph of species range and distribution
```
```
Graph of species range and distribution within the plot (plot location)
```
Picture of tree cores (with a small blurb)

## Rosaceae
### *Amelanchier arborea*	(Michx. f.) Fern. ```Downy Serviceberry```
```
Life history (information will be added by Michael)
```
```
Leaf traits (written about or scanned and labeled)
```
```
Annual Recruitment and Mortality
# of trees (stems) in 2013 and 2018:
5-year mortality of trees (stems):
new tree recuitment:
max DBH in sample:
mean DBH in sample:
```
```
Graph of recruiment and mortality
{r echo=false}
hist()
```
```
Graph of species range and distribution
```
```
Graph of species range and distribution within the plot (plot location)
```
Picture of tree cores (with a small blurb)

### *Crataegus pruniosa*	(Waxyfruit hawthorn)
```
Life history (information will be added by Michael)
```
```
Leaf traits (written about or scanned and labeled)
```
```
Annual Recruitment and Mortality
# of trees (stems) in 2013 and 2018:
5-year mortality of trees (stems):
new tree recuitment:
max DBH in sample:
mean DBH in sample:
```
```
Graph of recruiment and mortality
{r echo=false}
hist()
```
```
Graph of species range and distribution
```
```
Graph of species range and distribution within the plot (plot location)
```
Picture of tree cores (with a small blurb)

### *Prunus avium* (L.) L. ```Sweet cherry```
```
Life history (information will be added by Michael)
**Also known by common name Bird Cherry**
```
```
Leaf traits (written about or scanned and labeled)
```
```
Annual Recruitment and Mortality
# of trees (stems) in 2013 and 2018:
5-year mortality of trees (stems):
new tree recuitment:
max DBH in sample:
mean DBH in sample:
```
```
Graph of recruiment and mortality
{r echo=false}
hist()
```
```
Graph of species range and distribution
```
```
Graph of species range and distribution within the plot (plot location)
```
Picture of tree cores (with a small blurb)

### *Prunus persica* (L.) Batsch ```Peach```
```
Life history (information will be added by Michael)
```
```
Leaf traits (written about or scanned and labeled)
```
```
Annual Recruitment and Mortality
# of trees (stems) in 2013 and 2018:
5-year mortality of trees (stems):
new tree recuitment:
max DBH in sample:
mean DBH in sample:
```
```
Graph of recruiment and mortality
{r echo=false}
hist()
```
```
Graph of species range and distribution
```
```
Graph of species range and distribution within the plot (plot location)
```
Picture of tree cores (with a small blurb)

### *Prunus serotina* Ehrh. var serotina	```Black Cherry```
```
Life history (information will be added by Michael)
**Common name is also Wild Black Cherry.**
```
```
Leaf traits (written about or scanned and labeled)
```
```
Annual Recruitment and Mortality
# of trees (stems) in 2013 and 2018:
5-year mortality of trees (stems):
new tree recuitment:
max DBH in sample:
mean DBH in sample:
```
```
Graph of recruiment and mortality
{r echo=false}
hist()
```
```
Graph of species range and distribution
```
```
Graph of species range and distribution within the plot (plot location)
```
Picture of tree cores (with a small blurb)

### *Rosa multiflora* Thunb. ex Murr.	```Multiflora Rose```
```
Life history (information will be added by Michael)
```
```
Leaf traits (written about or scanned and labeled)
```
```
Annual Recruitment and Mortality
# of trees (stems) in 2013 and 2018:
5-year mortality of trees (stems):
new tree recuitment:
max DBH in sample:
mean DBH in sample:
```
```
Graph of recruiment and mortality
{r echo=false}
hist()
```
```
Graph of species range and distribution
```
```
Graph of species range and distribution within the plot (plot location)
```
Picture of tree cores (with a small blurb)

### *Rubus allegheniensis* Porter ```Allegheny Blackberry```
```
Life history (information will be added by Michael)
```
```
Leaf traits (written about or scanned and labeled)
```
```
Annual Recruitment and Mortality
# of trees (stems) in 2013 and 2018:
5-year mortality of trees (stems):
new tree recuitment:
max DBH in sample:
mean DBH in sample:
```
```
Graph of recruiment and mortality
{r echo=false}
hist()
```
```
Graph of species range and distribution
```
```
Graph of species range and distribution within the plot (plot location)
```
Picture of tree cores (with a small blurb)

### *Rubus pensilvanicus*	Poir. ```Pennsylvania Blackberry```
```
Life history (information will be added by Michael)
**This plant is also affectionally known as Prickly Blackberry.**
```
```
Leaf traits (written about or scanned and labeled)
```
```
Annual Recruitment and Mortality
# of trees (stems) in 2013 and 2018:
5-year mortality of trees (stems):
new tree recuitment:
max DBH in sample:
mean DBH in sample:
```
```
Graph of recruiment and mortality
{r echo=false}
hist()
```
```
Graph of species range and distribution
```
```
Graph of species range and distribution within the plot (plot location)
```
Picture of tree cores (with a small blurb)

*Rubus phoenicolasius* Maxim.	```Wineberry```
```
Life history (information will be added by Michael)
```
```
Leaf traits (written about or scanned and labeled)
```
```
Annual Recruitment and Mortality
# of trees (stems) in 2013 and 2018:
5-year mortality of trees (stems):
new tree recuitment:
max DBH in sample:
mean DBH in sample:
```
```
Graph of recruiment and mortality
{r echo=false}
hist()
```
```
Graph of species range and distribution
```
```
Graph of species range and distribution within the plot (plot location)
```
Picture of tree cores (with a small blurb)

## Sapindaceae
### *Acer negundo* L. var negundo ```Boxelder```
```
Life history (information will be added by Michael)
**Second common name is Eastern Boxelder.**
```
```
Leaf traits (written about or scanned and labeled)
```
```
Annual Recruitment and Mortality
# of trees (stems) in 2013 and 2018:
5-year mortality of trees (stems):
new tree recuitment:
max DBH in sample:
mean DBH in sample:
```
```
Graph of recruiment and mortality
{r echo=false}
hist()
```
```
Graph of species range and distribution
```
```
Graph of species range and distribution within the plot (plot location)
```
Picture of tree cores (with a small blurb)

### *Acer platanoides* L.	```Norway Maple```
```
Life history (information will be added by Michael)
```
```
Leaf traits (written about or scanned and labeled)
```
```
Annual Recruitment and Mortality
# of trees (stems) in 2013 and 2018:
5-year mortality of trees (stems):
new tree recuitment:
max DBH in sample:
mean DBH in sample:
```
```
Graph of recruiment and mortality
{r echo=false}
hist()
```
```
Graph of species range and distribution
```
```
Graph of species range and distribution within the plot (plot location)
```
Picture of tree cores (with a small blurb)

### *Acer rubrum*	L. ```Red Maple```
```
Life history (information will be added by Michael)
```
```
Leaf traits (written about or scanned and labeled)
```
```
Annual Recruitment and Mortality
# of trees (stems) in 2013 and 2018:
5-year mortality of trees (stems):
new tree recuitment:
max DBH in sample:
mean DBH in sample:
```
```
Graph of recruiment and mortality
{r echo=false}
hist()
```
```
Graph of species range and distribution
```
```
Graph of species range and distribution within the plot (plot location)
```
Picture of tree cores (with a small blurb)

## Simaroubaceae
### *Ailanthus altissima* (P. Miller) Swingle ```Tree of Heaven```
```
Life history (information will be added by Michael)
```
```
Leaf traits (written about or scanned and labeled)
```
```
Annual Recruitment and Mortality
# of trees (stems) in 2013 and 2018:
5-year mortality of trees (stems):
new tree recuitment:
max DBH in sample:
mean DBH in sample:
```
```
Graph of recruiment and mortality
{r echo=false}
hist()
```
```
Graph of species range and distribution
```
```
Graph of species range and distribution within the plot (plot location)
```
Picture of tree cores (with a small blurb)

## Ulmaceae
### *Ulmus americana*	L. ```American Elm```
```
Life history (information will be added by Michael)
```
```
Leaf traits (written about or scanned and labeled)
```
```
Annual Recruitment and Mortality
# of trees (stems) in 2013 and 2018:
5-year mortality of trees (stems):
new tree recuitment:
max DBH in sample:
mean DBH in sample:
```
```
Graph of recruiment and mortality
{r echo=false}
hist()
```
```
Graph of species range and distribution
```
```
Graph of species range and distribution within the plot (plot location)
```
Picture of tree cores (with a small blurb)

### *Ulmus rubra*	Muhl. ```Slippery Elm```
```
Life history (information will be added by Michael)
**Species is also commonly known as Red Elm.**
```
```
Leaf traits (written about or scanned and labeled)
```
```
Annual Recruitment and Mortality
# of trees (stems) in 2013 and 2018:
5-year mortality of trees (stems):
new tree recuitment:
max DBH in sample:
mean DBH in sample:
```
```
Graph of recruiment and mortality
{r echo=false}
hist()
```
```
Graph of species range and distribution
```
```
Graph of species range and distribution within the plot (plot location)
```
Picture of tree cores (with a small blurb)


# Chapter 5: Biotic Drivers of Change
## Invasive Plants
(insert Caroline's information here - should include description/life history, native range, range in US, spread in pot, and data from the Shenandoah paper)

## Invasive Species and Pathogens
(expand on data found in Shenandoah paper)

## Impact of Deer and Plant Ecology
(Bill's section - include that the deer exclosure has also led to greater numbers of species)

## Interspecies Competition
(could talk about how different species fight for available space, i.e. tree fall gaps)


# Chapter 6: Carbon Cycling
(take it away Krista!)